---
title: "Basel Biometric Section (BBS): Upcoming events"
author: ""
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

# Upcoming events

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## upcoming   
path <- getwd()
upcoming <- as.data.frame(read_excel(paste(path, "/data/upcoming.xlsx", sep = ""), col_types = NULL))

# prepare date strings
dates <- unique(select(upcoming, Date))[, 1]
d <- substr(dates, 1, 2)
m <- substr(dates, 4, 5)
y <- substr(dates, 7, 11)

rdate <- paste(y, m, d, sep = "")

upcoming$Registration <- paste("[Registration](", select(upcoming, Registration)[, 1], ")", sep = "")
upcoming$Agenda <- paste("[Agenda](talks/", rdate, "/agenda.pdf)", sep = "")

upcoming[is.na(upcoming)] <- ""
```

```{r, include=TRUE, echo=FALSE}
kable(upcoming)
```