---
title: "Basel Biometric Society (BBS): Upcoming events"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

# Upcoming events
  
```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## upcoming   
path <- getwd()
upcoming <- as.data.frame(read_excel(paste(path, "/data/upcoming.xlsx", sep = ""), col_types = NULL))

if (nrow(upcoming) > 0){
  # prepare date strings
  dates <- unique(select(upcoming, date))[, 1]
  d <- substr(dates, 1, 2)
  m <- substr(dates, 4, 5)
  y <- substr(dates, 7, 11)

  rdate <- paste(y, m, d, sep = "")

  upcoming$Registration <- ifelse(is.na(select(upcoming, registration)[, 1]), "", 
                                  paste("[Registration](", select(upcoming, registration)[, 1], ")", sep = ""))
  ag <- file.exists(paste("upcoming/", rdate, "/agenda.pdf", sep = ""))
  upcoming$Agenda <- ifelse(ag, paste("[Agenda](upcoming/", rdate, "/agenda.pdf)", sep = ""), "")
  upcoming[upcoming$date == "20.02.2025", "Registration"] <- "[Registration for the event](https://docs.google.com/forms/d/e/1FAIpQLSdBQBsPYqv65htk3XKUYyYzpe8cCOJE12edltFy5m7VmJj6Cw/viewform)<br><br>[Application for mentors](https://docs.google.com/forms/d/e/1FAIpQLSeNESs9AJKrUXmLBv_wiiHKjWJHWEJ2nq89ZiS3SPLfy4JMfw/viewform)<br><br>[Application for mentees](https://docs.google.com/forms/d/e/1FAIpQLSeURnmnkwiuZkw0v45tBPdHQ1ameYc1xLx7de2zHOsdErplHg/viewform) (will open after the event)"

  upcoming[is.na(upcoming)] <- ""

  upcoming <- select(upcoming, date, event, type, Agenda, Registration, comment) %>% rename("Date" = date, "Event" = event, "Type of event" = type, 
                                                                                            "Comment" = comment)
}
```

```{r, include=TRUE, echo=FALSE}
if (nrow(upcoming) > 0){kable(upcoming)} else {kable("No upcoming events announced yet. Check back later!", col.names = "")}
```


