---
title: "Updates on this page"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

* 2025/06/13: Added June BBS NextGen Lunch.
* 2025/06/02: Uploaded first announcement for [Colloquium in Honor of Hans Ulrich Burger on the Occasion of His Retirement from Roche](events_upcoming.html).
* 2025/04/30: Uploaded save-the-date for [BBS NextGen Seminar "Building Bridges: Communication Across Academia, Industry, and Regulators"](events_upcoming.html).
* 2025/03/25: Added slides for [BBS Face-to-Face Meeting on Covariate Adjustment in Clinical Trials](events_past.html#bbs-face-to-face-meeting-on-covariate-adjustment-in-clinical-trials)
* 2025/03/24: Added recording for [BBS Webinar "From Statistical Innovations to Common Practice: How to innovate with impact?"](events_past.html#bbs-webinar-on-from-statistical-innovations-to-common-practice-how-to-innovate-with-impact).
* 2025/02/19: Uploaded final announcement for [BBS Meeting on Covariate adjustment in clinical trials](events_upcoming.html)
* 2025/02/11: Uploaded announcement for [BBS Webinar "From Statistical Innovations to Common Practice: How to innovate with impact?"](events_past.html#bbs-webinar-on-from-statistical-innovations-to-common-practice-how-to-innovate-with-impact).
* 2025/02/06: Uploaded first announcement for [BBS Meeting on Covariate adjustment in clinical trials](events_upcoming.html)
* 2025/01/11: Uploaded announcement for next [BBS Next Generation Lunch](events_upcoming.html)
* 2024/11/29: Uploaded first announcement for the [BBS Next Generation Mentoring Program](events_upcoming.html)
* 2024/11/19: Uploaded first announcement for training course [Do you speak statistics? - How do you work as a statistician in a cross-functional team?](events_upcoming.html)
* 2024/10/23: Added recordings and slidedecks for webinar [Patient-Focused Drug Development: The Role of Patient Preference Studies](events_past.html#patient-focused-drug-development-the-role-of-patient-preference-studies).
* 2024/09/30: Added recordings for [AI in Clinical Research and Drug Development](events_past.html#ai-in-clinical-research-and-drug-development-and-bbs-general-assembly).
* 2024/09/26: Uploaded slides for [AI in Clinical Research and Drug Development](events_past.html#ai-in-clinical-research-and-drug-development-and-bbs-general-assembly).
* 2024/09/09: Uploaded final announcement for [AI in Clinical Research and Drug Development and BBS General Assembly](events_upcoming.html).
* 2024/09/02: Uploaded slides for [Controlling the chances of false discoveries in exploratory analysis of clinical trials](events_past.html#controlling-the-chances-of-false-discoveries-in-exploratory-analysis-of-clinical-trials).
* 2024/08/23: Uploaded final announcement for [Thriving Careers: Navigating Bias, Reinventing Yourself, and Essential Skills for Employability](events_upcoming.html).
* 2024/08/07: Uploaded first announcement for [Patient-Focused Drug Development: The Role of Patient Preference Studies](events_upcoming.html).
* 2024/08/06: Added [BBS Next Generation committee page](nextgen.html)
* 2024/08/05: Uploaded first announcement for [AI in Clinical Research and Drug Development and BBS General Assembly](events_upcoming.html).
* 2024/07/15: Uploaded first announcement for Next Generation event [Thriving Careers: Navigating Bias, Reinventing Yourself, and Essential Skills for Employability](events_upcoming.html).
* 2024/05/23: Uploaded slides for [Essentials of Medical Data Sharing and Privacy - Maximize the use of data](events_past.html#essentials-of-medical-data-sharing-and-privacy-maximize-the-use-of-data).
* 2024/04/30: Uploaded final announcement and agenda for hybrid event [Essentials of Medical Data Sharing and Privacy - Maximize the use of data](events_upcoming.html).
* 2024/04/22: Uploaded first announcement for virtual event [Controlling the chances of false discoveries in exploratory analysis of clinical trials](events_upcoming.html).
* 2024/04/16: Uploaded slides and recordings for [BBS Seminar: Reproducibility in Biomedical Research](events_past.html#reproducibility-in-biomedical-research).
* 2024/03/22: Uploaded first announcement and agenda for hybrid event [Essentials of Medical Data Sharing and Privacy - Maximize the use of data](events_upcoming.html).
* 2024/02/20: Uploaded first announcement for [Next Generation event on visualization](events_upcoming.html).
* 2024/02/07: Uploaded first announcement for [Reproducibility in biomedical research](events_upcoming.html).
* 2024/01/30: Uploaded slides for [Estimands in Early Development (ED) Across Therapeutic Areas](events_past.html#estimands-in-early-development-ed-across-therapeutic-areas).
* 2024/01/29: Added summary of [expectations for BBS board members](data/BBS_Council_Members_Expectations.pdf).
* 2024/01/08: Congratulations to Lilla di Scala for being the new BBS president! And we welcome two new board members, Dominic Magirr (Novartis) and Andreas Ziegler (Cardio-CARE, Medizincampus Davos), see [board](board.html).
* 2023/12/20: Uploaded final announcement for [BBS Training: Causal thinking in clinical trials](events_upcoming.html).
* 2023/12/07: Uploaded slides for [Next Generation BBS Training Day](trainings_past.html#next-generation-bbs-training-day).
* 2023/11/06: Uploaded slides and recordings for [BBS Annual Meeting: Federated learning and new data modalities](events_past.html#federated-learning-and-new-data-modalities).
* 2023/11/01: Added registration link for [Next Generation BBS Training Day](events_upcoming.html).
* 2023/10/13: Added slidedecks to webinar [Pre-approval and Post-approval Challenges in the Clinical Development and Reimbursement of CAR-T Cell Therapies](events_past.html#pre-approval-and-post-approval-challenges-in-the-clinical-development-and-reimbursement-of-car-t-cell-therapies). Uploaded final agenda/announcement for [BBS Annual Meeting: Federated learning and new data modalities](events_upcoming.html).
* 2023/10/10: Uploaded agenda/first announcement for [Next Generation BBS Training Day](events_upcoming.html).
* 2023/09/28: Uploaded final agenda for webinar [Pre-approval and Post-approval Challenges in the Clinical Development and Reimbursement of CAR-T Cell Therapies](events_upcoming.html).
* 2023/09/03: Uploaded link to materials of [Advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact](trainings/20230903/20230903_gsd_adaptive.html).
* 2023/08/31: Uploaded 2nd announcement for webinar [Pre-approval and Post-approval Challenges in the Clinical Development and Reimbursement of CAR-T Cell Therapies](events_upcoming.html).
* 2023/08/08: Added first announcement for [BBS Annual Meeting: Federated learning and new data modalities](events_upcoming.html).
* 2023/07/21: Added further slidedecks to [NextGen seminar](events_past.html#next-generation-event-on-soft-skills-professional-development-and-networking).
* 2023/07/05: Uploaded 1st announcement and registration link for (free) webinar [Pre-approval and Post-approval Challenges in the Clinical Development and Reimbursement of CAR-T Cell Therapies](events_upcoming.html). Added Kaspar Rufibach's slidedeck to [NextGen seminar](events_past.html#next-generation-event-on-soft-skills-professional-development-and-networking).
* 2023/05/23: Uploaded agenda and registration link for workshop [Estimands in Early Development (ED) across Therapeutic Areas](events_past.html#next-generation-event-on-soft-skills-professional-development-and-networking).
* 2023/05/02: Uploaded agenda and registration link for seminar [Next Generation event on soft-skills, professional development, and networking](events_upcoming.html).
* 2023/04/13: Uploaded slides and recordings for [BBS seminar "Quantification of risk: ask the right questions or time to apply the estimand framework to safety!"](events_past.html#quantification-of-risk-ask-the-right-questions-or-time-to-apply-the-estimand-framework-to-safety).
* 2023/03/21: Uploaded slides and added time stamps to recording for [Joint BES / BBS seminar "Real-World Data Quality – Assessing data quality and demonstrating fitness-for-purpose"](events_past.html#joint-besbbs-webinar-real-world-data-quality).
* 2023/03/15: Uploaded link to recording for [Joint BES / BBS seminar "Real-World Data Quality – Assessing data quality and demonstrating fitness-for-purpose"](events_past.html#joint-besbbs-webinar-real-world-data-quality).
* 2023/03/08: First announcement of seminar [Next Generation event on soft-skills, professional development, and networking](events_upcoming.html).
* 2023/10/02: Added announcement of seminar [Joint BES / BBS seminar "Real-World Data Quality – Assessing data quality and demonstrating fitness-for-purpose"](events_upcoming.html).
* 2023/10/02: Added materials of an amazing training [Good Software Engineering
Practice for R Packages](https://kkmann.github.io/workshop-r-swe/).
* 2023/01/17: Added announcement of workshop [Adaptive Designs and Multiple Testing Procedures Workshop](events_upcoming.html).
* 2023/01/09: Added announcement of seminar [Quantification of risk: ask the right questions or time to apply the estimand framework to safety!](events_upcoming.html).
* 2022/12/16: Added recording and slide decks of [joint EFSPI & BBS virtual event on "Addressing intercurrent events: Treatment policy and hypothetical strategies (Day 2)"](events_past.html#joint-efspi-bbs-virtual-event---addressing-intercurrent-events-treatment-policy-and-hypothetical-strategies-day-2).
* 2022/12/14: Added recording of [Next Generation Networking Seminar](events_past.html#next-generation-networking-seminar).
* 2022/12/09: Added recording and slide decks of [joint EFSPI & BBS virtual event on "Addressing intercurrent events: Treatment policy and hypothetical strategies (Day 1)"](events_past.html#joint-efspi-bbs-virtual-event---addressing-intercurrent-events-treatment-policy-and-hypothetical-strategies-day-1).
* 2022/11/25: Moved this page to [quarto](https://quarto.org/) implying a slightly different look.
* 2022/09/19: Added final version of material of BBS course [Advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact](trainings/20220913/20220913_gsd_adaptive.html).
* 2022/07/20: Added recording and slide decks of seminar ["On market approval and market access: Breaking the linear thinking or how to innovate in a crowded space?"](events_past.html#on-market-approval-and-market-access-breaking-the-linear-thinking-or-how-to-innovate-in-a-crowded-space).
* 2022/07/01: Added recording, slide decks of [seminar on "Registry studies and health technology assessment (HTA)"](events_past.html#23062022:_BBS__EFSPI_Seminar_Registry_studies_and_HTA).
* 2022/06/15: Added 1st announcement of [seminar on "On market approval and market access: Breaking the linear thinking or how to innovate in a crowded space?"](events_upcoming.html).
* 2022/05/31: Added recording, slidedeck of [transforming drug development and BBS assembly](events_past.html#24052022:_BBS_Spring_Seminar_Transforming_drug_development_and_Assembly).
* 2022/05/21: Added 2nd announcement of [seminar on "Registry studies and HTA"](events_upcoming.html).
* 2022/05/13: Location has changed for [spring seminar on "Transforming drug development" and bi-yearly BBS assembly](events_upcoming.html). Note, the new location is: Novartis Campus, Auditorium 510_U1
* 2022/04/20: Training on advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact is FULLY BOOKED.
* 2022/04/11: Added announcement of [spring seminar on "Transforming drug development"](events_upcoming.html).
* 2022/03/30: Added recording, slidedeck of [graphical approaches to multiple test problems training](trainings_past.html#29032022:_Graphical_approaches_to_multiple_test_problems).
* 2022/03/21: Added announcement of [seminar on "Registry studies and health technology assessment (HTA)"](events_upcoming.html).
* 2022/03/15: Added recording, slidedeck, exercises (incl. dataset) of [machine learning training](trainings_past.html#21022022:_Machine_Learning_in_clinical_drug_development).
* 2022/02/28: Added new version of [statutes](data/BBS_Statutes.pdf) with minor updates.






