<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kaspar Rufibach (Roche), Marc Vandemeulebroecke (Novartis), Gernot Wassmer (rpact), Marcel Wolbers (Roche)">
<meta name="dcterms.date" content="2022-12-22">

<title>Basel Biometrics Society - Solutions to the exercises for the BBS course ‘Advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact’ on 13Sep2022</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Basel Biometrics Society</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about-bbs" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">About BBS</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about-bbs">    
        <li>
    <a class="dropdown-item" href="../../purpose.html" rel="" target="">
 <span class="dropdown-text">Purpose</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../board.html" rel="" target="">
 <span class="dropdown-text">BBS board</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../updates.html" rel="" target="">
 <span class="dropdown-text">Updates on this page</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-upcoming-events" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Upcoming events</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-upcoming-events">    
        <li>
    <a class="dropdown-item" href="../../events_upcoming.html" rel="" target="">
 <span class="dropdown-text">Announcements of upcoming events</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-past-seminars" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Past seminars</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-past-seminars">    
        <li>
    <a class="dropdown-item" href="../../events_past.html" rel="" target="">
 <span class="dropdown-text">Agendas, slidedecks, and recordings of past BBS seminars</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-past-trainings" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">Past trainings</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-past-trainings">    
        <li>
    <a class="dropdown-item" href="../../trainings_past.html" rel="" target="">
 <span class="dropdown-text">Agendas, slidedecks, and recordings of past BBS training events</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../additional_docs.html" rel="" target="">
 <span class="menu-text">Additional documents</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul class="collapse">
  <li><a href="#purpose-of-this-document" id="toc-purpose-of-this-document" class="nav-link active" data-scroll-target="#purpose-of-this-document">Purpose of this document</a></li>
  <li><a href="#load-rpact" id="toc-load-rpact" class="nav-link" data-scroll-target="#load-rpact">Load <code>rpact</code></a></li>
  <li><a href="#exercise-1-group-sequential-survival-trial-with-efficacy-and-futility-interim-analyses" id="toc-exercise-1-group-sequential-survival-trial-with-efficacy-and-futility-interim-analyses" class="nav-link" data-scroll-target="#exercise-1-group-sequential-survival-trial-with-efficacy-and-futility-interim-analyses">Exercise 1 (Group-sequential survival trial with efficacy and futility interim analyses)</a>
  <ul class="collapse">
  <li><a href="#exercise-1a-sample-size-calculation" id="toc-exercise-1a-sample-size-calculation" class="nav-link" data-scroll-target="#exercise-1a-sample-size-calculation">Exercise 1a (Sample size calculation)</a></li>
  <li><a href="#exercise-1b-addition-of-a-futility-interim-analysis" id="toc-exercise-1b-addition-of-a-futility-interim-analysis" class="nav-link" data-scroll-target="#exercise-1b-addition-of-a-futility-interim-analysis">Exercise 1b (Addition of a futility interim analysis)</a></li>
  <li><a href="#exercise-1c-power-loss-associated-with-the-futility-interim-analysis" id="toc-exercise-1c-power-loss-associated-with-the-futility-interim-analysis" class="nav-link" data-scroll-target="#exercise-1c-power-loss-associated-with-the-futility-interim-analysis">Exercise 1c (Power loss associated with the futility interim analysis)</a></li>
  <li><a href="#bonus-exercise-1d-timing-of-os-events" id="toc-bonus-exercise-1d-timing-of-os-events" class="nav-link" data-scroll-target="#bonus-exercise-1d-timing-of-os-events">Bonus Exercise 1d (Timing of OS events)</a></li>
  </ul></li>
  <li><a href="#exercise-2-adaptive-trial-with-a-continuous-endpoint" id="toc-exercise-2-adaptive-trial-with-a-continuous-endpoint" class="nav-link" data-scroll-target="#exercise-2-adaptive-trial-with-a-continuous-endpoint">Exercise 2 (Adaptive trial with a continuous endpoint)</a>
  <ul class="collapse">
  <li><a href="#exercise-2a-the-alpha-calculus" id="toc-exercise-2a-the-alpha-calculus" class="nav-link" data-scroll-target="#exercise-2a-the-alpha-calculus">Exercise 2a (the “alpha calculus”)</a></li>
  <li><a href="#exercise-2b-early-stopping-and-sample-size-adaptation" id="toc-exercise-2b-early-stopping-and-sample-size-adaptation" class="nav-link" data-scroll-target="#exercise-2b-early-stopping-and-sample-size-adaptation">Exercise 2b (early stopping and sample size adaptation)</a></li>
  <li><a href="#exercise-2c-final-inference" id="toc-exercise-2c-final-inference" class="nav-link" data-scroll-target="#exercise-2c-final-inference">Exercise 2c (final inference)</a></li>
  </ul></li>
  <li><a href="#exercise-3-sample-size-calculation-for-testing-proportions" id="toc-exercise-3-sample-size-calculation-for-testing-proportions" class="nav-link" data-scroll-target="#exercise-3-sample-size-calculation-for-testing-proportions">Exercise 3 (Sample size calculation for testing proportions)</a>
  <ul class="collapse">
  <li><a href="#exercise-3a-sample-size-calculation" id="toc-exercise-3a-sample-size-calculation" class="nav-link" data-scroll-target="#exercise-3a-sample-size-calculation">Exercise 3a (sample size calculation)</a></li>
  <li><a href="#exercise-3b-boundary-plots" id="toc-exercise-3b-boundary-plots" class="nav-link" data-scroll-target="#exercise-3b-boundary-plots">Exercise 3b (boundary plots)</a></li>
  <li><a href="#exercise-3c-power-assessment" id="toc-exercise-3c-power-assessment" class="nav-link" data-scroll-target="#exercise-3c-power-assessment">Exercise 3c (power assessment)</a></li>
  <li><a href="#exercise-3d-power-illustration" id="toc-exercise-3d-power-illustration" class="nav-link" data-scroll-target="#exercise-3d-power-illustration">Exercise 3d (power illustration)</a></li>
  </ul></li>
  <li><a href="#exercise-4-sample-size-reassessment-for-testing-proportions" id="toc-exercise-4-sample-size-reassessment-for-testing-proportions" class="nav-link" data-scroll-target="#exercise-4-sample-size-reassessment-for-testing-proportions">Exercise 4 (Sample size reassessment for testing proportions)</a>
  <ul class="collapse">
  <li><a href="#exercise-4a-assess-power" id="toc-exercise-4a-assess-power" class="nav-link" data-scroll-target="#exercise-4a-assess-power">Exercise 4a (assess power)</a></li>
  <li><a href="#exercise-4b-illustrate-power-difference" id="toc-exercise-4b-illustrate-power-difference" class="nav-link" data-scroll-target="#exercise-4b-illustrate-power-difference">Exercise 4b (illustrate power difference)</a></li>
  <li><a href="#exercise-4c-histogram-of-sample-sizes" id="toc-exercise-4c-histogram-of-sample-sizes" class="nav-link" data-scroll-target="#exercise-4c-histogram-of-sample-sizes">Exercise 4c (histogram of sample sizes)</a></li>
  </ul></li>
  <li><a href="#exercise-5-multi-armed-design-with-continuous-endpoint" id="toc-exercise-5-multi-armed-design-with-continuous-endpoint" class="nav-link" data-scroll-target="#exercise-5-multi-armed-design-with-continuous-endpoint">Exercise 5 (Multi-armed design with continuous endpoint)</a>
  <ul class="collapse">
  <li><a href="#exercise-5a-first-stage-and-conditional-power" id="toc-exercise-5a-first-stage-and-conditional-power" class="nav-link" data-scroll-target="#exercise-5a-first-stage-and-conditional-power">Exercise 5a (First stage and conditional power)</a></li>
  <li><a href="#exercise-5b-second-stage" id="toc-exercise-5b-second-stage" class="nav-link" data-scroll-target="#exercise-5b-second-stage">Exercise 5b (Second stage)</a></li>
  <li><a href="#exercise-5c-intersection-tests" id="toc-exercise-5c-intersection-tests" class="nav-link" data-scroll-target="#exercise-5c-intersection-tests">Exercise 5c (Intersection tests)</a></li>
  </ul></li>
  <li><a href="#bonus-exercise-6-planning-of-survival-design" id="toc-bonus-exercise-6-planning-of-survival-design" class="nav-link" data-scroll-target="#bonus-exercise-6-planning-of-survival-design">Bonus Exercise 6 (Planning of survival design)</a>
  <ul class="collapse">
  <li><a href="#exercise-6a-accrual-and-follow-up-time-given" id="toc-exercise-6a-accrual-and-follow-up-time-given" class="nav-link" data-scroll-target="#exercise-6a-accrual-and-follow-up-time-given">Exercise 6a (accrual and follow-up time given)</a></li>
  <li><a href="#exercise-6b-follow-up-time-and-absolue-intensity-given" id="toc-exercise-6b-follow-up-time-and-absolue-intensity-given" class="nav-link" data-scroll-target="#exercise-6b-follow-up-time-and-absolue-intensity-given">Exercise 6b (follow-up time and absolue intensity given)</a></li>
  <li><a href="#exercise-6c-accrual-time-and-max-number-of-patients-given" id="toc-exercise-6c-accrual-time-and-max-number-of-patients-given" class="nav-link" data-scroll-target="#exercise-6c-accrual-time-and-max-number-of-patients-given">Exercise 6c (accrual time and max number of patients given)</a></li>
  <li><a href="#exercise-6d-staggered-patient-entry" id="toc-exercise-6d-staggered-patient-entry" class="nav-link" data-scroll-target="#exercise-6d-staggered-patient-entry">Exercise 6d (staggered patient entry)</a></li>
  </ul></li>
  <li><a href="#bonus-exercise-7-adaptive-survival-design" id="toc-bonus-exercise-7-adaptive-survival-design" class="nav-link" data-scroll-target="#bonus-exercise-7-adaptive-survival-design">Bonus Exercise 7 (Adaptive survival design)</a>
  <ul class="collapse">
  <li><a href="#exercise-7a-verify-results-by-simulation" id="toc-exercise-7a-verify-results-by-simulation" class="nav-link" data-scroll-target="#exercise-7a-verify-results-by-simulation">Exercise 7a (verify results by simulation)</a></li>
  <li><a href="#exercise-7b-assess-adaptive-survival-design" id="toc-exercise-7b-assess-adaptive-survival-design" class="nav-link" data-scroll-target="#exercise-7b-assess-adaptive-survival-design">Exercise 7b (assess adaptive survival design)</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Solutions to the exercises for the BBS course ‘Advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact’ on 13Sep2022</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Kaspar Rufibach (Roche), Marc Vandemeulebroecke (Novartis), Gernot Wassmer (rpact), Marcel Wolbers (Roche) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 22, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="purpose-of-this-document" class="level1 unnumbered">
<h1 class="unnumbered">Purpose of this document</h1>
<p>This R markdown file provides solutions to the exercises of the BBS course “Advanced group-sequential and adaptive confirmatory clinical trial designs, with R practicals using rpact”.</p>
<p>All materials related to this course are available on the BBS webpage at this <a href="https://baselbiometrics.github.io/home/docs/trainings/20220913/20220913_gsd_adaptive.html">link</a>.</p>
</section>
<section id="load-rpact" class="level1 unnumbered">
<h1 class="unnumbered">Load <code>rpact</code></h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load rpact</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpact)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">packageVersion</span>(<span class="st">"rpact"</span>) <span class="co"># version should be version 3.0 or higher</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] '3.3.1'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setLogLevel</span>(<span class="st">"DISABLED"</span>) <span class="co"># disable progress messages from e.g. getAnalysisResults </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Also load tictoc for timing of the simulations</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tictoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-1-group-sequential-survival-trial-with-efficacy-and-futility-interim-analyses" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 1 (Group-sequential survival trial with efficacy and futility interim analyses)</h1>
<p>Assume we plan a phase III, randomized, multicenter, open-label, two-arm trial with a time-to-event endpoint of OS. The <strong>general assumptions for the sample size assessment</strong> are:</p>
<ul>
<li>2:1 randomization.</li>
<li>Uniform recruitment of 480 patients over 10 months (48 per month).</li>
<li>The dropout rate is 5% in both arms over 12 months.</li>
</ul>
<p>The <strong>sample size section for OS</strong> states that the following additional assumptions were made:</p>
<ul>
<li>Exponentially distributed OS in the control arm with a median of 12 months.</li>
<li>Median OS improvement vs.&nbsp;control of 4.9 months (medians 16.9 vs.&nbsp;12 months, i.e.&nbsp;a HR of approximately 0.71).</li>
<li>Log-rank test at a two-sided significance level of 0.05, power 80%.</li>
<li>One interim analyses for efficacy (IA) and one final analysis using the O'Brien-Fleming boundaries approximated using the Lan-DeMets method. The first IA will be performed after 60% of information.</li>
</ul>
<section id="exercise-1a-sample-size-calculation" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-1a-sample-size-calculation">Exercise 1a (Sample size calculation)</h2>
<p>Calculate the required number of events and timing of analysis for OS using the information fraction of 60%. Use the <code>rpact</code> functions <code>getDesignGroupSequential</code> and <code>getSampleSizeSurvival</code>.</p>
<p><strong>Solution:</strong> We perform calculations at a one-sided significance level of 2.5% which gives the same sample size but is more compatible with the futility interim added in Part 1b.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># basic parameters</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>infofrac <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.6</span>, <span class="dv">1</span>)   <span class="co"># information fractions</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>         <span class="co"># one-sided</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>accrualTime <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>accrualIntensity <span class="ot">&lt;-</span> <span class="dv">48</span>  <span class="co"># 48 pts over 10 months</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>randoratio <span class="ot">&lt;-</span> <span class="dv">2</span>         <span class="co"># 2:1 randomization</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="dv">12</span>                <span class="co"># median control</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fl">16.9</span>              <span class="co"># median treatment</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>do <span class="ot">&lt;-</span> <span class="fl">0.05</span>              <span class="co"># dropout same in both arms</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>doTime <span class="ot">&lt;-</span> <span class="dv">12</span>            <span class="co"># time at which dropout happens</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>maxn <span class="ot">&lt;-</span> accrualIntensity <span class="sc">*</span> accrualTime[<span class="dv">2</span>]</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify the group-sequential design </span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>design1 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">sided =</span> <span class="dv">1</span>, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">informationRates =</span> infofrac, <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate sample size for OS for this design</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>sampleSizeOS1 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(design1,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">allocationRatioPlanned =</span> randoratio,    </span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">median2 =</span> m2, <span class="at">median1 =</span> m1, </span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">dropoutRate1 =</span> do, <span class="at">dropoutRate2 =</span> do, <span class="at">dropoutTime =</span> doTime,</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">accrualTime =</span> accrualTime, <span class="at">accrualIntensity =</span> accrualIntensity)  </span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="co"># rpact summary</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sampleSizeOS1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size calculation for a survival endpoint

Sequential analysis with a maximum of 2 looks (group sequential design), overall 
significance level 2.5% (one-sided).
The sample size was calculated for a two-sample logrank test, 
H0: hazard ratio = 1, H1: treatment median(1) = 16.9, control median(2) = 12, 
planned allocation ratio = 2, accrual time = 10, accrual intensity = 48, 
dropout rate(1) = 0.05, dropout rate(2) = 0.05, dropout time = 12, power 80%.

Stage                                         1      2 
Information rate                            60%   100% 
Efficacy boundary (z-value scale)         2.669  1.981 
Overall power                            0.3123 0.8000 
Expected number of subjects               480.0 
Number of subjects                        480.0  480.0 
Cumulative number of events               182.3  303.8 
Analysis time                              15.8   28.7 
Expected study duration                    24.7 
Cumulative alpha spent                   0.0038 0.0250 
One-sided local significance level       0.0038 0.0238 
Efficacy boundary (t)                     0.658  0.786 
Exit probability for efficacy (under H0) 0.0038 
Exit probability for efficacy (under H1) 0.3123 

Legend:
  (t): treatment effect scale</code></pre>
</div>
</div>
</section>
<section id="exercise-1b-addition-of-a-futility-interim-analysis" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-1b-addition-of-a-futility-interim-analysis">Exercise 1b (Addition of a futility interim analysis)</h2>
<p>Now add an interim analysis for futility ONLY (i.e.&nbsp;no stopping for efficacy possible) after 30% of information where we stop the trial if the observed hazard ratio is above 1.</p>
<p>Hint: Use significance levels from design with efficacy only, add futility interim with minimal alpha-spending. The argument <code>userAlphaSpending</code> in <code>getDesignGroupSequential</code> helps.</p>
<p><strong>Solution:</strong></p>
<p>We spend a minimal alpha of 0.00001 at the futility interim analysis and use the alpha-spending from the O’Brien-Fleming-type alpha-spending function for the efficacy interim and the final analysis. In rpact, the <code>futilityBounds</code> are specified on the <span class="math inline">\(Z\)</span>-scale and an observed hazard ratio 1 at the futility interim corresponds to a <span class="math inline">\(Z\)</span>-score of 0. This leads to the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add the futility using the sig levels computed above and spending epsilon alpha at the futility</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>design2 <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, infofrac),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">sided =</span> <span class="dv">1</span>, <span class="at">alpha =</span> alpha, <span class="at">beta =</span> beta,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">typeOfDesign =</span> <span class="st">"asUser"</span>, </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">userAlphaSpending =</span> <span class="fu">c</span>(<span class="dv">0</span>, design1<span class="sc">$</span>alphaSpent),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">futilityBounds =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="sc">-</span><span class="cn">Inf</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">bindingFutility =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate sample size for this design</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>sampleSizeOS2 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(design2,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">allocationRatioPlanned =</span> randoratio,    </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">median2 =</span> m2, <span class="at">median1 =</span> m1, </span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">dropoutRate1 =</span> do, <span class="at">dropoutRate2 =</span> do, <span class="at">dropoutTime =</span> doTime,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">accrualTime =</span> accrualTime, <span class="at">accrualIntensity =</span> accrualIntensity)  </span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># rpact summary</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sampleSizeOS2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size calculation for a survival endpoint

Sequential analysis with a maximum of 3 looks (group sequential design), overall 
significance level 2.5% (one-sided).
The sample size was calculated for a two-sample logrank test, 
H0: hazard ratio = 1, H1: treatment median(1) = 16.9, control median(2) = 12, 
planned allocation ratio = 2, accrual time = 10, accrual intensity = 48, 
dropout rate(1) = 0.05, dropout rate(2) = 0.05, dropout time = 12, power 80%.

Stage                                         1      2      3 
Information rate                            30%    60%   100% 
Efficacy boundary (z-value scale)           Inf  2.669  1.981 
Futility boundary (z-value scale)             0   -Inf 
Overall power                                 0 0.3361 0.8000 
Expected number of subjects               480.0 
Number of subjects                        480.0  480.0  480.0 
Cumulative number of events                96.9  193.7  322.9 
Analysis time                              10.1   16.7   31.7 
Expected study duration                    25.5 
Cumulative alpha spent                        0 0.0038 0.0250 
One-sided local significance level            0 0.0038 0.0238 
Efficacy boundary (t)                         0  0.666  0.791 
Futility boundary (t)                     1.000        
Overall exit probability (under H0)      0.5000 0.0038 
Overall exit probability (under H1)      0.0561 0.3361 
Exit probability for efficacy (under H0)      0 0.0038 
Exit probability for efficacy (under H1)      0 0.3361 
Exit probability for futility (under H0) 0.5000      0 
Exit probability for futility (under H1) 0.0561      0 

Legend:
  (t): treatment effect scale</code></pre>
</div>
</div>
<p>We see that by adding the futility interim we increase the maximal number of events from 303.827705 to 322.8702626.</p>
</section>
<section id="exercise-1c-power-loss-associated-with-the-futility-interim-analysis" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-1c-power-loss-associated-with-the-futility-interim-analysis">Exercise 1c (Power loss associated with the futility interim analysis)</h2>
<p>How large is the power loss from adding this futility interim analysis, assuming we would not increase the number of events compared to the initial design above?</p>
<p>To compute the power loss of adding the futility, <em>conservatively</em> assuming it will be adhered to, i.e.&nbsp;we compute the power of the design <em>with</em> futility using the number of events of the design <em>without</em> futility.</p>
<p><strong>Solution:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># power of design with futility at the number of events without futility</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>power <span class="ot">&lt;-</span> <span class="fu">getPowerSurvival</span>(design2, <span class="at">allocationRatioPlanned =</span> randoratio, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">maxNumberOfEvents =</span> <span class="fu">ceiling</span>(sampleSizeOS1<span class="sc">$</span>maxNumberOfEvents),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">median2 =</span> m2, <span class="at">median1 =</span> m1, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dropoutRate1 =</span> do, <span class="at">dropoutRate2 =</span> do, <span class="at">dropoutTime =</span> doTime,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">accrualTime =</span> accrualTime, <span class="at">accrualIntensity =</span> accrualIntensity,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># power, as compared to the specified 80%</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>power<span class="sc">$</span>overallReject</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7763167</code></pre>
</div>
</div>
<p>So the power loss of adding the futility amounts to 0.0236833.</p>
</section>
<section id="bonus-exercise-1d-timing-of-os-events" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="bonus-exercise-1d-timing-of-os-events">Bonus Exercise 1d (Timing of OS events)</h2>
<p>How many OS events would be expected to occur until exactly 16 and 24 months, respectively, from first patient randomized?</p>
<p>Hint: <code>getEventProbabilities</code>.</p>
<p><strong>Solution:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability of an event until 16 months and 24 months  </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>probOS <span class="ot">&lt;-</span> <span class="fu">getEventProbabilities</span>(<span class="at">time =</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">24</span>), </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">allocationRatioPlanned =</span> randoratio,    </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lambda2 =</span> <span class="fu">getLambdaByMedian</span>(m2),<span class="at">lambda1 =</span> <span class="fu">getLambdaByMedian</span>(m1),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dropoutRate1 =</span> do, <span class="at">dropoutRate2 =</span> do, <span class="at">dropoutTime =</span> doTime,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">accrualTime =</span> accrualTime, <span class="at">accrualIntensity =</span> accrualIntensity)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>probOS</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Event probabilities at given time:

User defined parameters:
  Time                                         : 16.00, 24.00 
  Accrual time                                 : 10.00 
  Accrual intensity                            : 48.0 
  lambda(1)                                    : 0.041 
  lambda(2)                                    : 0.0578 
  Planned allocation ratio                     : 2 
  Drop-out rate (1)                            : 0.050 
  Drop-out rate (2)                            : 0.050 

Default parameters:
  kappa                                        : 1 
  Drop-out time                                : 12.00 

Time and output:
  Hazard ratio                                 : 0.710 
  Maximum number of subjects                   : 480 
  Cumulative event probabilities               : 0.3847, 0.5595 
  Event probabilities (1)                      : 0.3506, 0.5193 
  Event probabilities (2)                      : 0.4529, 0.6400 

Legend:
  (i): values of treatment arm i</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Expected number of OS events </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>maxn <span class="sc">*</span> probOS<span class="sc">$</span>overallEventProbabilities</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 184.6677 268.5770</code></pre>
</div>
</div>
<p>Expected number of events are 185 and 269 until months 16 and 24, respecticely.</p>
<hr>
</section>
</section>
<section id="exercise-2-adaptive-trial-with-a-continuous-endpoint" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 2 (Adaptive trial with a continuous endpoint)</h1>
<p>A confirmatory, randomized and blinded study of an investigational drug against Placebo is planned in mild to moderate Alzheimer’s disease. The primary endpoint is the change from baseline in ADAS-Cog, a neuropsychological test battery measuring cognitive abilities, assessed 6 months after treatment initiation. The ADAS-Cog has a range of 0-70; we reverse its scale so that greater values are good. We consider our primary endpoint as approximately normally distributed, and for simplicity we assume a known standard deviation of 10. We believe that the improvement in the primary endpoint that can be achieved with the investigational drug is at least 4 points better than that under Placebo; and we want to have 80% chance of achieving a significant result if this is indeed the case. However, if the investigational drug is no better than Placebo, we want to have no more than 2.5% chance to claim success. This yields a sample size of approximately n=100 per treatment group for a trial with fixed sample size.</p>
<section id="exercise-2a-the-alpha-calculus" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-2a-the-alpha-calculus">Exercise 2a (the “alpha calculus”)</h2>
<p>We want to build in a “sanity check” mid-way through the trial. More precisely, we implement an interim analysis using the inverse normal method, with the following characteristics (all with respect to the primary endpoint):</p>
<ul>
<li><p>Stop for futility if the investigational drug appears worse than Placebo</p></li>
<li><p>Stop for efficacy if the investigational drug appears “very significantly better” than Placebo (<span class="math inline">\(p &lt; 0.0001\)</span>)</p></li>
</ul>
<p>Which set of <span class="math inline">\((\alpha,\alpha_0,\alpha_1,\alpha_2)\)</span> satisfies these conditions?</p>
<p>Hint: Use <code>getDesignInverseNormal</code> with a user-defined alpha-spending function and a binding futility boundary.</p>
<p><strong>Solution:</strong></p>
<p>The exercise specifies alpha=0.025, alpha0=0.5 (equivalent to a binding futility boundary at a <span class="math inline">\(Z\)</span>-score of 0), and alpha1=0.0001. We compute alpha2 as follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">getDesignInverseNormal</span>(<span class="at">typeOfDesign =</span> <span class="st">"asUser"</span>, <span class="at">userAlphaSpending =</span> <span class="fu">c</span>(<span class="fl">0.0001</span>,<span class="fl">0.025</span>), </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">futilityBounds =</span> <span class="dv">0</span>, <span class="at">bindingFutility =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Design parameters and output of inverse normal combination test design:

User defined parameters:
  Type of design                               : User defined alpha spending 
  Futility bounds (binding)                    : 0.000 
  Binding futility                             : TRUE 
  User defined alpha spending                  : 0.0001, 0.0250 

Derived from user defined parameters:
  Maximum number of stages                     : 2 
  Stages                                       : 1, 2 
  Information rates                            : 0.500, 1.000 

Default parameters:
  Significance level                           : 0.0250 
  Type II error rate                           : 0.2000 
  Two-sided power                              : FALSE 
  Test                                         : one-sided 
  Tolerance                                    : 1e-08 
  Type of beta spending                        : none 

Output:
  Cumulative alpha spending                    : 0.0001, 0.0250 
  Critical values                              : 3.719, 1.955 
  Stage levels (one-sided)                     : 0.00010, 0.02531 </code></pre>
</div>
</div>
<p>This yields <span class="math inline">\(\alpha_2\)</span> = d$stageLevels[2] = 0.0253.</p>
<p><strong>What regulatory issues could this raise?</strong></p>
<p><strong>Solution</strong> The Regulator may not like that the final test is performed at a greater level (<span class="math inline">\(\alpha_2\)</span>) than the overall level (<span class="math inline">\(\alpha\)</span>). This is caused by cutting off a greater rejection region by the futility stop (right of <span class="math inline">\(\alpha_0\)</span>) than adding to it by the efficacy stop (left of <span class="math inline">\(\alpha_1\)</span>), and by compensating for this imbalance through a higher conditional error function (<span class="math inline">\(\alpha_2 &gt; \alpha\)</span>; so-called “buy-back alpha” from the futility stop).</p>
</section>
<section id="exercise-2b-early-stopping-and-sample-size-adaptation" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-2b-early-stopping-and-sample-size-adaptation">Exercise 2b (early stopping and sample size adaptation)</h2>
<ol type="1">
<li>At the interim analysis after <span class="math inline">\(n_1\)</span> = 50 patients per group, we observe an average ADAS-Cog improvement of 4 points under the investigational drug and of 1 point under Placebo. Should we stop or continue the trial?</li>
</ol>
<p>Hint: <code>getDataset</code> to define the input dataset and <code>getAnalysisResults</code> to analyse it.</p>
<p><strong>Solution</strong></p>
<p>We should continue the trial, since our drug is neither worse nor very significantly better than Placebo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(<span class="at">means1 =</span> <span class="dv">4</span>, <span class="at">means2 =</span> <span class="dv">1</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stDev1 =</span> <span class="dv">10</span>, <span class="at">stDev2 =</span> <span class="dv">10</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">n1 =</span> <span class="dv">50</span>, <span class="at">n2 =</span> <span class="dv">50</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>result1 <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> d, <span class="at">dataInput =</span> dat, <span class="at">nPlanned =</span> <span class="dv">100</span>,<span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(result1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis results for a continuous endpoint

Sequential analysis with 2 looks (inverse normal combination test design).
The results were calculated using a two-sample t-test (one-sided), 
normal approximation test, equal variances option.
H0: mu(1) - mu(2) = 0 against H1: mu(1) - mu(2) &gt; 0. 
The conditional power calculation with planned sample size is based on 
overall effect = 3 and overall standard deviation = 10.

Stage                                                 1                2 
Fixed weight                                      0.707            0.707 
Efficacy boundary (z-value scale)                 3.719            1.955 
Futility boundary (z-value scale)                     0 
Cumulative alpha spent                          &lt;0.0001           0.0250 
Stage level                                     &lt;0.0001           0.0253 
Cumulative effect size                            3.000                  
Cumulative (pooled) standard deviation           10.000                  
Stage-wise test statistic                         1.500                  
Stage-wise p-value                               0.0668                  
Inverse normal combination                        1.500                  
Test action                                    continue                  
Conditional rejection probability                0.1030                  
Planned sample size                                                  100 
Conditional power                                                 0.5931 
95% repeated confidence interval        [-4.438; 10.438]                 
Repeated p-value                                                         </code></pre>
</div>
</div>
<p><span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(p_1=0.0668\)</span>, and <span class="math inline">\(\alpha_1=0.0001&lt;0.0668&lt;0.5=\alpha_0\)</span>.</p>
<ol start="2" type="1">
<li>At the same time, there is a change in strategy, and we now want 90% power at an improvement of 4 points over placebo. Determine the sample size per treatment group for the second stage of the trial, in light of the interim results.</li>
</ol>
<p>Hint: Calculate second stage sample size using <code>getSampleSizeMeans</code> with type I error equal to the conditional rejection probability from the previous part.</p>
<p><strong>Solution</strong></p>
<p>We compute the sample size necessary for 90% conditional power; we round up and check:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getSampleSizeMeans</span>(<span class="at">alpha=</span>result1<span class="sc">$</span>conditionalRejectionProbabilities[<span class="dv">1</span>], <span class="at">beta =</span> <span class="fl">0.1</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">alternative =</span> <span class="dv">4</span>, <span class="at">stDev =</span> <span class="dv">10</span>, <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>nFixed</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 162.0456</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>result2 <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> d, <span class="at">dataInput =</span> dat, <span class="at">nPlanned =</span> <span class="dv">164</span>, <span class="at">thetaH1 =</span> <span class="dv">4</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">assumedStDev =</span> <span class="dv">10</span>, <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(result2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis results for a continuous endpoint

Sequential analysis with 2 looks (inverse normal combination test design).
The results were calculated using a two-sample t-test (one-sided), 
normal approximation test, equal variances option.
H0: mu(1) - mu(2) = 0 against H1: mu(1) - mu(2) &gt; 0. 
The conditional power calculation with planned sample size is based on 
assumed effect = 4 and assumed standard deviation = 10.

Stage                                                 1                2 
Fixed weight                                      0.707            0.707 
Efficacy boundary (z-value scale)                 3.719            1.955 
Futility boundary (z-value scale)                     0 
Cumulative alpha spent                          &lt;0.0001           0.0250 
Stage level                                     &lt;0.0001           0.0253 
Cumulative effect size                            3.000                  
Cumulative (pooled) standard deviation           10.000                  
Stage-wise test statistic                         1.500                  
Stage-wise p-value                               0.0668                  
Inverse normal combination                        1.500                  
Test action                                    continue                  
Conditional rejection probability                0.1030                  
Planned sample size                                                  164 
Conditional power                                                 0.9027 
95% repeated confidence interval        [-4.438; 10.438]                 
Repeated p-value                                                         </code></pre>
</div>
</div>
<p><span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(n_2=82\)</span> per treatment group</p>
</section>
<section id="exercise-2c-final-inference" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-2c-final-inference">Exercise 2c (final inference)</h2>
<p>In the second stage of the trial, we observe an average ADAS-Cog improvement of only <strong>3 points</strong> under the investigational drug and of 1 point under Placebo.</p>
<ol type="1">
<li>Can we reject the null hypothesis and claim superiority of the investigational drug over placebo?</li>
</ol>
<p><strong>Solution</strong></p>
<p>Using the inverse normal method as planned, we can reject the null hypothesis and claim superiority of the investigational drug over placebo. More precisely, the combination test statistic after the second stage is 1.966, exceeding the critical value <span class="math inline">\(u_{0.0253}=1.955\)</span> (where <span class="math inline">\(u_\alpha\)</span> is the <span class="math inline">\((1-\alpha)\)</span>-quantile of <span class="math inline">\(N(0,1)\)</span>). Note that we test at the local level <span class="math inline">\(\alpha_2=0.0253\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(<span class="at">means1 =</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">3</span>), <span class="at">means2 =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">stDev1 =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>), <span class="at">stDev2 =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>),</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">n1 =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">82</span>), <span class="at">n2 =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">82</span>))</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">getAnalysisResults</span>(<span class="at">design =</span> d, <span class="at">dataInput =</span> dat2, <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis results for a continuous endpoint

Sequential analysis with 2 looks (inverse normal combination test design).
The results were calculated using a two-sample t-test (one-sided), 
normal approximation test, equal variances option.
H0: mu(1) - mu(2) = 0 against H1: mu(1) - mu(2) &gt; 0.

Stage                                                 1                2 
Fixed weight                                      0.707            0.707 
Efficacy boundary (z-value scale)                 3.719            1.955 
Futility boundary (z-value scale)                     0 
Cumulative alpha spent                          &lt;0.0001           0.0250 
Stage level                                     &lt;0.0001           0.0253 
Cumulative effect size                            3.000            2.379 
Cumulative (pooled) standard deviation           10.000            9.968 
Stage-wise test statistic                         1.500            1.281 
Stage-wise p-value                               0.0668           0.1002 
Inverse normal combination                        1.500            1.966 
Test action                                    continue           reject 
Conditional rejection probability                0.1030                  
95% repeated confidence interval        [-4.438; 10.438] [0.014 ; 4.863 ]
Repeated p-value                                                         
Final p-value                                                     0.0243 
Final confidence interval                                  [0.014; 4.933]
Median unbiased estimate                                           2.450 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Compute the overall (“exact”) p-value and confidence interval for the adaptive trial.</li>
</ol>
<p><strong>Solution</strong></p>
<p>From the commands above we also obtain: <span class="math inline">\(p=0.02435; \; CI=(0.014,4.93)\)</span></p>
<ol start="3" type="1">
<li>What would a “naive” z-test have concluded, based on all observations and ignoring the adaptive nature of the trial? What is your interpretation of the situation?</li>
</ol>
<p><strong>Solution</strong></p>
<p>A “naive” z-test would not have been able to reject the null hypothesis:</p>
<p><span class="math display">\[z = \sqrt{\frac{n_1 + n_2}{2}}\frac{\bar x - \bar y}{\sigma} = \sqrt{\frac{132}{2}} \frac{\frac{50\cdot 4 + 82 \cdot 3}{132}- 1}{10} = 1.9325 &lt; 1.960 = u_{0.025}\]</span></p>
<p>In rpact, use the following commands:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dGS <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">typeOfDesign =</span> <span class="st">"asUser"</span>, <span class="at">userAlphaSpending =</span> <span class="fu">c</span>(<span class="fl">0.0001</span>,<span class="fl">0.025</span>),</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">futilityBounds =</span> <span class="dv">0</span>, <span class="at">bindingFutility =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>dat3 <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(<span class="at">cumulativeMeans1 =</span> <span class="fu">c</span>(<span class="dv">4</span>,(<span class="dv">50</span><span class="sc">*</span><span class="dv">4</span><span class="sc">+</span><span class="dv">82</span><span class="sc">*</span><span class="dv">3</span>)<span class="sc">/</span><span class="dv">132</span>), <span class="at">cumulativeMeans2 =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cumulativeStDev1 =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>), <span class="at">cumulativeStDev2 =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>), </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">cumulativeN1 =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">132</span>), <span class="at">cumulativeN2 =</span> <span class="fu">c</span>(<span class="dv">50</span>,<span class="dv">132</span>))</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">getAnalysisResults</span>(<span class="at">design =</span> dGS, <span class="at">dataInput =</span> dat3, <span class="at">normalApproximation =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis results for a continuous endpoint

Sequential analysis with 2 looks (group sequential design).
The results were calculated using a two-sample t-test (one-sided), 
normal approximation test, equal variances option.
H0: mu(1) - mu(2) = 0 against H1: mu(1) - mu(2) &gt; 0.

Stage                                                 1                2 
Fixed weight                                        0.5                1 
Efficacy boundary (z-value scale)                 3.719            1.955 
Futility boundary (z-value scale)                     0 
Cumulative alpha spent                          &lt;0.0001           0.0250 
Stage level                                     &lt;0.0001           0.0253 
Cumulative effect size                            3.000            2.379 
Cumulative (pooled) standard deviation           10.000           10.000 
Overall test statistic                            1.500            1.933 
Overall p-value                                  0.0668           0.0266 
Test action                                    continue           accept 
Conditional rejection probability                0.1030                  
95% repeated confidence interval        [-4.438; 10.438] [-0.027; 4.785 ]
Repeated p-value                                                         
Final p-value                                                     0.0263 
Final confidence interval                                 [-0.027; 4.816]
Median unbiased estimate                                           2.390 </code></pre>
</div>
</div>
<p>Note that the definition of dat3 with the “cumulative” commands is necessary because otherwise always a “global” variance (accounting for the mean difference in the stages) is calculated.</p>
<p>Here we ignore the adaptive nature of the trial: we lump all data together (ignoring the sample size adaptation), and we test at the nominal level <span class="math inline">\(\alpha =0.025\)</span> (ignoring the possibility of early stopping). The second stage of the trial, showing less of a treatment effect, carries greater weight in this “naive” (that is, incorrect) version of the test. Note that it can go both ways: in other examples, the adaptive (correct) version of the test may be the one that fails to reject the null hypothesis. In less borderline situations, both tests will lead to the same conclusion. Proposals have been made in the literature for dealing with borderline situations.</p>
<hr>
</section>
</section>
<section id="exercise-3-sample-size-calculation-for-testing-proportions" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 3 (Sample size calculation for testing proportions)</h1>
<p>Suppose a trial should be conducted in 3 stages where at the first stage 50%, at the second stage 75%, and at the final stage 100% of the information should be observed. O’Brien-Fleming boundaries should be used with one-sided <span class="math inline">\(\alpha = 0.025\)</span> and non-binding futility bounds 0 and 0.5 for the first and the second stage, respectively, on the z-value scale.</p>
<p>The endpoints are binary (failure rates) and should be compared in a parallel group design, i.e., the null hypothesis to be tested is <span class="math inline">\(H_0:\pi_1 - \pi_2 = 0\,,\)</span> which is tested against the alternative <span class="math inline">\(H_1: \pi_1 - \pi_2 &lt; 0\,.\)</span></p>
<section id="exercise-3a-sample-size-calculation" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-3a-sample-size-calculation">Exercise 3a (sample size calculation)</h2>
<p>What is the necessary sample size to achieve 90% power if the failure rates are assumed to be <span class="math inline">\(\pi_1 = 0.40\)</span> and <span class="math inline">\(\pi_2 = 0.60\)</span>? What is the optimum allocation ratio?</p>
<p><strong>Solution</strong></p>
<p>The summary command provides a table for the study design parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>dGS <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.75</span>,<span class="dv">1</span>), <span class="at">alpha =</span> <span class="fl">0.025</span>, <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">typeOfDesign =</span> <span class="st">"OF"</span>, <span class="at">futilityBounds =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">getSampleSizeRates</span>(dGS, <span class="at">pi1 =</span> <span class="fl">0.4</span>, <span class="at">pi2 =</span> <span class="fl">0.6</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size calculation for a binary endpoint

Sequential analysis with a maximum of 3 looks (group sequential design), overall 
significance level 2.5% (one-sided).
The sample size was calculated for a two-sample test for rates 
(normal approximation),
H0: pi(1) - pi(2) = 0, H1: treatment rate pi(1) = 0.4, control rate pi(2) = 0.6, 
power 90%.

Stage                                         1      2      3 
Information rate                            50%    75%   100% 
Efficacy boundary (z-value scale)         2.863  2.337  2.024 
Futility boundary (z-value scale)             0  0.500 
Overall power                            0.2958 0.6998 0.9000 
Expected number of subjects               198.3 
Number of subjects                        133.1  199.7  266.3 
Cumulative alpha spent                   0.0021 0.0105 0.0250 
One-sided local significance level       0.0021 0.0097 0.0215 
Efficacy boundary (t)                    -0.248 -0.165 -0.124 
Futility boundary (t)                     0.000 -0.035 
Overall exit probability (under H0)      0.5021 0.2275 
Overall exit probability (under H1)      0.3058 0.4095 
Exit probability for efficacy (under H0) 0.0021 0.0083 
Exit probability for efficacy (under H1) 0.2958 0.4040 
Exit probability for futility (under H0) 0.5000 0.2191 
Exit probability for futility (under H1) 0.0100 0.0056 

Legend:
  (t): treatment effect scale</code></pre>
</div>
</div>
<p>The optimum allocation ratio is 1 in this case but calculated numerically, therefore slightly unequal 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">getSampleSizeRates</span>(dGS, <span class="at">pi1 =</span> <span class="fl">0.4</span>, <span class="at">pi2 =</span> <span class="fl">0.6</span>, <span class="at">allocationRatioPlanned =</span> <span class="dv">0</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>r<span class="sc">$</span>allocationRatioPlanned</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9999976</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(r<span class="sc">$</span>allocationRatioPlanned,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
</section>
<section id="exercise-3b-boundary-plots" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-3b-boundary-plots">Exercise 3b (boundary plots)</h2>
<p>Illustrate the decision boundaries on different scales.</p>
<p><strong>Solution</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(r, <span class="at">type =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(r, <span class="at">type =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-26-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(r, <span class="at">type =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-26-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="exercise-3c-power-assessment" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-3c-power-assessment">Exercise 3c (power assessment)</h2>
<p>Suppose that <span class="math inline">\(N = 280\)</span> subjects were planned for the study. What is the power if the failure rate in the active treatment group is <span class="math inline">\(\pi_1 = 0.50\)</span>?</p>
<p><strong>Solution</strong></p>
<p>The power is much reduced as compared to the case pi1 = 0.4 (where it exceeds 90%):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>power <span class="ot">&lt;-</span> <span class="fu">getPowerRates</span>(dGS, <span class="at">maxNumberOfSubjects =</span> <span class="dv">280</span>, <span class="at">pi1 =</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.5</span>), <span class="at">pi2 =</span> <span class="fl">0.6</span>, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>power<span class="sc">$</span>overallReject</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.914045 0.377853</code></pre>
</div>
</div>
</section>
<section id="exercise-3d-power-illustration" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-3d-power-illustration">Exercise 3d (power illustration)</h2>
<p>Illustrate power, expected sample size, and early/futility stop for a range of alternative values.</p>
<p><strong>Solution</strong></p>
<p>Specifying pi1 = c(0.3,0.6) provides a range of power and ANS values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>power <span class="ot">&lt;-</span> <span class="fu">getPowerRates</span>(dGS, <span class="at">maxNumberOfSubjects =</span> <span class="dv">280</span>, <span class="at">pi1 =</span> <span class="fu">c</span>(<span class="fl">0.3</span>,<span class="fl">0.6</span>), <span class="at">pi2 =</span> <span class="fl">0.6</span>,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(power, <span class="at">type =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<hr>
</section>
</section>
<section id="exercise-4-sample-size-reassessment-for-testing-proportions" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 4 (Sample size reassessment for testing proportions)</h1>
<p>Using an adaptive design, the sample size from Example 3 in the last interim can be increased up to a 4-fold of the originally planned sample size for the last stage. Conditional power 90% <em>based on the observed effect sizes (failure rates)</em> is used to increase the sample size.</p>
<section id="exercise-4a-assess-power" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-4a-assess-power">Exercise 4a (assess power)</h2>
<p>Use the inverse normal method to allow for the sample size increase and compare the test characteristics with the group sequential design from Example 3.</p>
<p><strong>Solution</strong></p>
<p>Define the inverse normal design and perform two simulations, one without and one with SSR:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>dIN <span class="ot">&lt;-</span> <span class="fu">getDesignInverseNormal</span>(<span class="at">informationRates =</span> <span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.75</span>,<span class="dv">1</span>), <span class="at">alpha =</span> <span class="fl">0.025</span>, <span class="at">beta =</span> <span class="fl">0.1</span>,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">futilityBounds =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.5</span>))</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>maxiter <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>sim1 <span class="ot">&lt;-</span> <span class="fu">getSimulationRates</span>(dIN, <span class="at">plannedSubjects =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">210</span>,<span class="dv">280</span>), <span class="at">pi1 =</span> <span class="fu">seq</span>(<span class="fl">0.4</span>,<span class="fl">0.5</span>,<span class="fl">0.01</span>), <span class="at">pi2 =</span> <span class="fl">0.6</span>,</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">FALSE</span>, <span class="at">maxNumberOfIterations =</span> maxiter, <span class="at">conditionalPower =</span> <span class="fl">0.9</span>,</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">minNumberOfSubjectsPerStage =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">70</span>,<span class="dv">70</span>), <span class="at">maxNumberOfSubjectsPerStage =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">70</span>,<span class="dv">70</span>),</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">1234</span>)</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>sim2 <span class="ot">&lt;-</span> <span class="fu">getSimulationRates</span>(dIN, <span class="at">plannedSubjects =</span> <span class="fu">c</span>(<span class="dv">140</span>,<span class="dv">210</span>,<span class="dv">280</span>), <span class="at">pi1 =</span> <span class="fu">seq</span>(<span class="fl">0.4</span>,<span class="fl">0.5</span>,<span class="fl">0.01</span>), <span class="at">pi2 =</span> <span class="fl">0.6</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">FALSE</span>, <span class="at">maxNumberOfIterations =</span> maxiter, <span class="at">conditionalPower =</span> <span class="fl">0.9</span>, </span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">minNumberOfSubjectsPerStage =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">70</span>,<span class="dv">70</span>), <span class="at">maxNumberOfSubjectsPerStage =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">70</span>,<span class="dv">4</span><span class="sc">*</span><span class="dv">70</span>),</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">5678</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that the sample sizes will be calculated under the assumption that the <em>conditional power for the subsequent stage</em> is 90%. If the resulting sample size is larger, the upper bound (4*70 = 280) is used.</p>
</section>
<section id="exercise-4b-illustrate-power-difference" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-4b-illustrate-power-difference">Exercise 4b (illustrate power difference)</h2>
<p>Illustrate the gain in power when using the adaptive sample size recalculation.</p>
<p><strong>Solution</strong></p>
<p>We use ggplot2 for doing this. First, a data set df is defined with the additional variable SSR. Using mytheme and the following ggplots commands, the difference in power and ASN of the two strategies is illustrated. It shows that at least for effect difference &gt; 0.15 an overall power of more than around 85% can be achieved with the proposed sample size recalculation strategy.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>dataSim1 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(sim1, <span class="at">niceColumnNamesEnabled =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>dataSim2 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(sim2, <span class="at">niceColumnNamesEnabled =</span> <span class="cn">FALSE</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>dataSim1<span class="sc">$</span>SSR <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"no SSR"</span>, <span class="fu">nrow</span>(dataSim1))</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>dataSim2<span class="sc">$</span>SSR <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">"SSR"</span>, <span class="fu">nrow</span>(dataSim2))</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(dataSim1, dataSim2)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>myTheme <span class="ot">=</span> <span class="fu">theme</span>(</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>), <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>), <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>,<span class="at">hjust =</span> <span class="fl">0.5</span>), </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>,<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> df,<span class="fu">aes</span>(<span class="at">x =</span> effect,<span class="at">y =</span> overallReject, <span class="at">group =</span> SSR, <span class="at">color =</span> SSR)) <span class="sc">+</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> effect,<span class="at">y =</span> expectedNumberOfSubjects<span class="sc">/</span><span class="dv">400</span>, <span class="at">group =</span> SSR, <span class="at">color =</span> SSR), <span class="at">size =</span> <span class="fl">1.1</span>, </span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>( <span class="st">"Power"</span>,  <span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span> . <span class="sc">*</span> <span class="dv">400</span>, <span class="at">name =</span> <span class="st">"ASN"</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="fl">0.2</span>,<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="sc">+</span>  <span class="fu">xlab</span>(<span class="st">"effect"</span>) <span class="sc">+</span>  <span class="fu">ggtitle</span>(<span class="st">"Power and ASN"</span>,<span class="st">"Power solid, ASN dashed"</span>) <span class="sc">+</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">yintercept =</span> <span class="fl">0.8</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">yintercept =</span> <span class="fl">0.9</span>, <span class="at">linetype =</span> <span class="st">"dotted"</span>) <span class="sc">+</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">xintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.2</span>, <span class="sc">-</span><span class="fl">0.15</span>), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>  myTheme</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: for saving the plot, you could e.g. use the commented code below</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot2::ggsave(filename = "C:/yourdirectory/comparison.png",</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co">#        plot = ggplot2::last_plot(), device = NULL, path = NULL,</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co">#        scale = 1.2, width = 20, height = 12, units = "cm", dpi = 600, limitsize = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exercise-4c-histogram-of-sample-sizes" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-4c-histogram-of-sample-sizes">Exercise 4c (histogram of sample sizes)</h2>
<p>Create a histogram for the attained sample size of the study when using the adaptive sample size recalculation. How often will the maximum sample size be achieved?</p>
<p><strong>Solution</strong></p>
<p>With the getData command the simulation results are obtained. Depending on pi1, you can create the histogram of the simulated total sample size</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tictoc)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>simdata<span class="ot">&lt;-</span> <span class="fu">getData</span>(sim2)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(simdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   24488 obs. of  18 variables:
 $ iterationNumber          : num  1 1 2 3 4 4 5 6 6 6 ...
 $ stageNumber              : num  1 2 1 1 1 2 1 1 2 3 ...
 $ pi1                      : num  0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 ...
 $ pi2                      : num  0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 ...
 $ numberOfSubjects         : num  140 70 140 140 140 70 140 140 70 280 ...
 $ numberOfCumulatedSubjects: num  140 210 140 140 140 210 140 140 210 490 ...
 $ rejectPerStage           : num  0 1 1 1 0 1 1 0 0 1 ...
 $ futilityPerStage         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ testStatistic            : num  2.7 3.45 3.39 3.38 2.22 ...
 $ testStatisticsPerStage   : num  2.7 2.15 3.39 3.38 2.22 ...
 $ overallRate1             : num  0.386 0.381 0.386 0.343 0.343 ...
 $ overallRate2             : num  0.614 0.619 0.671 0.629 0.529 ...
 $ stagewiseRates1          : num  0.386 0.371 0.386 0.343 0.343 ...
 $ stagewiseRates2          : num  0.614 0.629 0.671 0.629 0.529 ...
 $ sampleSizesPerStage1     : num  70 35 70 70 70 35 70 70 35 140 ...
 $ sampleSizesPerStage2     : num  70 35 70 70 70 35 70 70 35 140 ...
 $ trialStop                : logi  FALSE TRUE TRUE TRUE FALSE TRUE ...
 $ conditionalPowerAchieved : num  NA 0.959 NA NA NA ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>simPart <span class="ot">&lt;-</span> simdata[simdata<span class="sc">$</span>pi1 <span class="sc">==</span> <span class="fl">0.5</span>,] </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tic</span>()</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>overallSampleSizes <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span>maxiter, <span class="cf">function</span>(i) <span class="fu">sum</span>(simPart[simPart<span class="sc">$</span>iterationNumber<span class="sc">==</span>i,]<span class="sc">$</span>numberOfSubjects))</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">toc</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.47 sec elapsed</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tic()</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># overallSampleSizes &lt;- numeric(maxiter)</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="co"># for (i in 1:maxiter) overallSampleSizes[i] &lt;- sum(simPart[simPart$iterationNumber==i,]$numberOfSubjects)</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># toc()</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(overallSampleSizes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="BBSadaptiveCourse13Sep2022_solutions_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>How often the maximum sample size is reached can be obtained as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>simdata<span class="ot">&lt;-</span> <span class="fu">getData</span>(sim2)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>simdataPart <span class="ot">&lt;-</span> simdata[simdata<span class="sc">$</span>pi1 <span class="sc">==</span> <span class="fl">0.5</span>,] </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>subjectsRange <span class="ot">&lt;-</span> <span class="fu">cut</span>(simdataPart<span class="sc">$</span>numberOfSubjects, <span class="fu">c</span>(<span class="dv">69</span>, <span class="dv">70</span>, <span class="dv">139</span>, <span class="dv">140</span>, <span class="dv">210</span>, <span class="dv">279</span>, <span class="dv">280</span>))</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(simdataPart<span class="sc">$</span>stageNumber,subjectsRange), <span class="at">margin =</span> <span class="dv">1</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   subjectsRange
    (69,70] (70,139] (139,140] (140,210] (210,279] (279,280]
  1     0.0      0.0     100.0       0.0       0.0       0.0
  2   100.0      0.0       0.0       0.0       0.0       0.0
  3     0.0      9.0       0.3       8.8       4.7      77.2</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="exercise-5-multi-armed-design-with-continuous-endpoint" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 5 (Multi-armed design with continuous endpoint)</h1>
<p>Suppose a trial is conducted with three active treatment arms (+ one control arm). An adaptive design using the equally weighted inverse normal method with two interim analyses using O’Brien &amp; Fleming boundaries is chosen where in both interim analyses a selection of treatment arms is foreseen (overall <span class="math inline">\(\alpha = 0.025\)</span> one-sided). It is decided to test the intersection tests in the closed system of hypotheses with Dunnett’s test. In the designing stage, it was decided to conduct the study with 20 patients per treatment arm and stage where at interim the sample size can be redefined.</p>
<section id="exercise-5a-first-stage-and-conditional-power" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-5a-first-stage-and-conditional-power">Exercise 5a (First stage and conditional power)</h2>
<p>Suppose, at the first stage, the following results were obtained:</p>
<table class="table">
<thead>
<tr class="header">
<th>arm</th>
<th>n</th>
<th>mean</th>
<th>std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>19</td>
<td>3.11</td>
<td>1.77</td>
</tr>
<tr class="even">
<td>2</td>
<td>22</td>
<td>3.87</td>
<td>1.23</td>
</tr>
<tr class="odd">
<td>3</td>
<td>23</td>
<td>4.12</td>
<td>1.64</td>
</tr>
<tr class="even">
<td>control</td>
<td>21</td>
<td>3.02</td>
<td>1.72</td>
</tr>
</tbody>
</table>
<p>Perform the closed test and assess the conditional power in order to decide which treatment arm(s) should be selected and if the sample size should be redefined.</p>
<p><strong>Solution</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dataExample <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1      =</span> <span class="fu">c</span>(<span class="dv">19</span>),</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2      =</span> <span class="fu">c</span>(<span class="dv">22</span>),</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n3      =</span> <span class="fu">c</span>(<span class="dv">23</span>),</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">n4      =</span> <span class="fu">c</span>(<span class="dv">21</span>),</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">means1  =</span> <span class="fu">c</span>(<span class="fl">3.11</span>),</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">means2  =</span> <span class="fu">c</span>(<span class="fl">3.87</span>),</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">means3  =</span> <span class="fu">c</span>(<span class="fl">4.12</span>),</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">means4  =</span> <span class="fu">c</span>(<span class="fl">3.02</span>),</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs1 =</span> <span class="fu">c</span>(<span class="fl">1.77</span>),</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs2 =</span> <span class="fu">c</span>(<span class="fl">1.23</span>),</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs3 =</span> <span class="fu">c</span>(<span class="fl">1.64</span>),</span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs4 =</span> <span class="fu">c</span>(<span class="fl">1.72</span>)</span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.025</span></span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>intersectionTest <span class="ot">&lt;-</span> <span class="st">"Dunnett"</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>varianceOption <span class="ot">&lt;-</span> <span class="st">"overallPooled"</span></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>normalApproximation <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="fu">getDesignInverseNormal</span>(<span class="at">kMax =</span> <span class="dv">3</span>, <span class="at">alpha =</span> alpha, <span class="at">typeOfDesign =</span> <span class="st">"OF"</span>)</span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a>stageResults <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> design,</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataInput =</span> dataExample, <span class="at">thetaH0 =</span> <span class="dv">0</span>, <span class="at">stage =</span> <span class="dv">1</span>,</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">TRUE</span>, <span class="at">normalApproximation =</span> normalApproximation,</span>
<span id="cb50-26"><a href="#cb50-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectionTest =</span> intersectionTest, <span class="at">varianceOption =</span> varianceOption,</span>
<span id="cb50-27"><a href="#cb50-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">nPlanned =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">40</span>))</span>
<span id="cb50-28"><a href="#cb50-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-29"><a href="#cb50-29" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stageResults)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multi-arm analysis results for a continuous endpoint (3 active arms vs. control)

Sequential analysis with 3 looks (inverse normal combination test design).
The results were calculated using a multi-arm t-test (one-sided), 
Dunnett intersection test, overall pooled variances option.
H0: mu(i) - mu(control) = 0 against H1: mu(i) - mu(control) &gt; 0. 
The conditional power calculation with planned sample size is based on 
overall effect: thetaH1(1) = 0.09, thetaH1(2) = 0.85, thetaH1(3) = 1.1 and 
overall standard deviation: sd(1) = 1.74, sd(2) = 1.49, sd(3) = 1.68.

Stage                                                   1               2               3 
Fixed weight                                        0.577           0.577           0.577 
Efficacy boundary (z-value scale)                   3.471           2.454           2.004 
Cumulative alpha spent                             0.0003          0.0072          0.0250 
Stage level                                        0.0003          0.0071          0.0225 
Cumulative effect size (1)                          0.090                                 
Cumulative effect size (2)                          0.850                                 
Cumulative effect size (3)                          1.100                                 
Cumulative (pooled) standard deviation              1.597                                 
Stage-wise test statistic (1)                       0.178                                 
Stage-wise test statistic (2)                       1.745                                 
Stage-wise test statistic (3)                       2.283                                 
Stage-wise p-value (1)                             0.4296                                 
Stage-wise p-value (2)                             0.0424                                 
Stage-wise p-value (3)                             0.0125                                 
Adjusted stage-wise p-value (1, 2, 3)              0.0325                                 
Adjusted stage-wise p-value (1, 2)                 0.0751                                 
Adjusted stage-wise p-value (1, 3)                 0.0232                                 
Adjusted stage-wise p-value (2, 3)                 0.0231                                 
Adjusted stage-wise p-value (1)                    0.4296                                 
Adjusted stage-wise p-value (2)                    0.0424                                 
Adjusted stage-wise p-value (3)                    0.0125                                 
Overall adjusted test statistic (1, 2, 3)           1.845                                 
Overall adjusted test statistic (1, 2)              1.439                                 
Overall adjusted test statistic (1, 3)              1.991                                 
Overall adjusted test statistic (2, 3)              1.994                                 
Overall adjusted test statistic (1)                 0.177                                 
Overall adjusted test statistic (2)                 1.724                                 
Overall adjusted test statistic (3)                 2.240                                 
Test action: reject (1)                             FALSE                                 
Test action: reject (2)                             FALSE                                 
Test action: reject (3)                             FALSE                                 
Conditional rejection probability (1)              0.0101                                 
Conditional rejection probability (2)              0.0831                                 
Conditional rejection probability (3)              0.1432                                 
Planned sample size                                                    40              40 
Conditional power (1)                                              0.0009          0.0182 
Conditional power (2)                                              0.4102          0.8723 
Conditional power (3)                                              0.6722          0.9652 
95% repeated confidence interval (1)       [-1.896; 2.076]                                
95% repeated confidence interval (2)       [-1.064; 2.764]                                
95% repeated confidence interval (3)       [-0.793; 2.993]                                
Repeated p-value (1)                                 &gt;0.5                                 
Repeated p-value (2)                               0.2633                                 
Repeated p-value (3)                               0.1794                                 

Legend:
  (i): results of treatment arm i vs. control arm
  (i, j, ...): comparison of treatment arms 'i, j, ...' vs. control arm</code></pre>
</div>
</div>
</section>
<section id="exercise-5b-second-stage" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-5b-second-stage">Exercise 5b (Second stage)</h2>
<p>Suppose it was decided to drop treatment arm 1 for stage 2 and leave the sample size for the remaining arms unchanged. For the second stage, the following results were obtained:</p>
<table class="table">
<thead>
<tr class="header">
<th>arm</th>
<th>n</th>
<th>mean</th>
<th>std</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>23</td>
<td>3.66</td>
<td>1.11</td>
</tr>
<tr class="even">
<td>3</td>
<td>19</td>
<td>3.98</td>
<td>1.21</td>
</tr>
<tr class="odd">
<td>control</td>
<td>22</td>
<td>2.99</td>
<td>1.82</td>
</tr>
</tbody>
</table>
<p>Perform the closed test and discuss whether or not to stop the study and determine overall <span class="math inline">\(p\,\)</span>-values and confidence intervals.</p>
<p><strong>Solution</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>dataExample <span class="ot">&lt;-</span> <span class="fu">getDataset</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">n1      =</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="cn">NA</span>),</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n2      =</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">23</span>),</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n3      =</span> <span class="fu">c</span>(<span class="dv">23</span>, <span class="dv">19</span>),</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">n4      =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">22</span>),</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">means1  =</span> <span class="fu">c</span>(<span class="fl">3.11</span>, <span class="cn">NA</span>),</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">means2  =</span> <span class="fu">c</span>(<span class="fl">3.87</span>, <span class="fl">3.66</span>),</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">means3  =</span> <span class="fu">c</span>(<span class="fl">4.12</span>, <span class="fl">3.98</span>),</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">means4  =</span> <span class="fu">c</span>(<span class="fl">3.02</span>, <span class="fl">2.99</span>),</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs1 =</span> <span class="fu">c</span>(<span class="fl">1.77</span>, <span class="cn">NA</span>),</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs2 =</span> <span class="fu">c</span>(<span class="fl">1.23</span>, <span class="fl">1.11</span>),</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs3 =</span> <span class="fu">c</span>(<span class="fl">1.64</span>, <span class="fl">1.21</span>),</span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">stDevs4 =</span> <span class="fu">c</span>(<span class="fl">1.72</span>, <span class="fl">1.82</span>)</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>stageResults <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> design,</span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataInput =</span> dataExample, <span class="at">thetaH0 =</span> <span class="dv">0</span>, <span class="at">stage =</span> <span class="dv">2</span>,</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">TRUE</span>, <span class="at">normalApproximation =</span> normalApproximation,</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectionTest =</span> intersectionTest, <span class="at">varianceOption =</span> varianceOption)</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stageResults)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multi-arm analysis results for a continuous endpoint (3 active arms vs. control)

Sequential analysis with 3 looks (inverse normal combination test design).
The results were calculated using a multi-arm t-test (one-sided), 
Dunnett intersection test, overall pooled variances option.
H0: mu(i) - mu(control) = 0 against H1: mu(i) - mu(control) &gt; 0.

Stage                                                   1               2               3 
Fixed weight                                        0.577           0.577           0.577 
Efficacy boundary (z-value scale)                   3.471           2.454           2.004 
Cumulative alpha spent                             0.0003          0.0072          0.0250 
Stage level                                        0.0003          0.0071          0.0225 
Cumulative effect size (1)                          0.090                                 
Cumulative effect size (2)                          0.850           0.758                 
Cumulative effect size (3)                          1.100           1.052                 
Cumulative (pooled) standard deviation              1.597           1.468                 
Stage-wise test statistic (1)                       0.178                                 
Stage-wise test statistic (2)                       1.745           1.582                 
Stage-wise test statistic (3)                       2.283           2.226                 
Stage-wise p-value (1)                             0.4296                                 
Stage-wise p-value (2)                             0.0424          0.0594                 
Stage-wise p-value (3)                             0.0125          0.0149                 
Adjusted stage-wise p-value (1, 2, 3)              0.0325          0.0274                 
Adjusted stage-wise p-value (1, 2)                 0.0751          0.0594                 
Adjusted stage-wise p-value (1, 3)                 0.0232          0.0149                 
Adjusted stage-wise p-value (2, 3)                 0.0231          0.0274                 
Adjusted stage-wise p-value (1)                    0.4296                                 
Adjusted stage-wise p-value (2)                    0.0424          0.0594                 
Adjusted stage-wise p-value (3)                    0.0125          0.0149                 
Overall adjusted test statistic (1, 2, 3)           1.845           2.662                 
Overall adjusted test statistic (1, 2)              1.439           2.121                 
Overall adjusted test statistic (1, 3)              1.991           2.945                 
Overall adjusted test statistic (2, 3)              1.994           2.767                 
Overall adjusted test statistic (1)                 0.177                                 
Overall adjusted test statistic (2)                 1.724           2.322                 
Overall adjusted test statistic (3)                 2.240           3.121                 
Test action: reject (1)                             FALSE           FALSE                 
Test action: reject (2)                             FALSE           FALSE                 
Test action: reject (3)                             FALSE            TRUE                 
Conditional rejection probability (1)              0.0101                                 
Conditional rejection probability (2)              0.0831          0.3184                 
Conditional rejection probability (3)              0.1432          0.6154                 
95% repeated confidence interval (1)       [-1.896; 2.076]                                
95% repeated confidence interval (2)       [-1.064; 2.764] [-0.203; 1.716]                
95% repeated confidence interval (3)       [-0.793; 2.993] [0.066 ; 2.022]                
Repeated p-value (1)                                 &gt;0.5                                 
Repeated p-value (2)                               0.2633          0.0476                 
Repeated p-value (3)                               0.1794          0.0162                 

Legend:
  (i): results of treatment arm i vs. control arm
  (i, j, ...): comparison of treatment arms 'i, j, ...' vs. control arm</code></pre>
</div>
</div>
</section>
<section id="exercise-5c-intersection-tests" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-5c-intersection-tests">Exercise 5c (Intersection tests)</h2>
<p>Would the Bonferroni and the Simes test intersection tests provide the same results?</p>
<p><strong>Solution</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>stageResults <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> design,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataInput =</span> dataExample, <span class="at">thetaH0 =</span> <span class="dv">0</span>, <span class="at">stage =</span> <span class="dv">2</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">TRUE</span>, <span class="at">normalApproximation =</span> normalApproximation,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectionTest =</span> <span class="st">"Bonferroni"</span>, <span class="at">varianceOption =</span> varianceOption)</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stageResults)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multi-arm analysis results for a continuous endpoint (3 active arms vs. control)

Sequential analysis with 3 looks (inverse normal combination test design).
The results were calculated using a multi-arm t-test (one-sided), 
Bonferroni intersection test, overall pooled variances option.
H0: mu(i) - mu(control) = 0 against H1: mu(i) - mu(control) &gt; 0.

Stage                                                   1               2               3 
Fixed weight                                        0.577           0.577           0.577 
Efficacy boundary (z-value scale)                   3.471           2.454           2.004 
Cumulative alpha spent                             0.0003          0.0072          0.0250 
Stage level                                        0.0003          0.0071          0.0225 
Cumulative effect size (1)                          0.090                                 
Cumulative effect size (2)                          0.850           0.758                 
Cumulative effect size (3)                          1.100           1.052                 
Cumulative (pooled) standard deviation              1.597           1.468                 
Stage-wise test statistic (1)                       0.178                                 
Stage-wise test statistic (2)                       1.745           1.582                 
Stage-wise test statistic (3)                       2.283           2.226                 
Stage-wise p-value (1)                             0.4296                                 
Stage-wise p-value (2)                             0.0424          0.0594                 
Stage-wise p-value (3)                             0.0125          0.0149                 
Adjusted stage-wise p-value (1, 2, 3)              0.0376          0.0297                 
Adjusted stage-wise p-value (1, 2)                 0.0848          0.0594                 
Adjusted stage-wise p-value (1, 3)                 0.0251          0.0149                 
Adjusted stage-wise p-value (2, 3)                 0.0251          0.0297                 
Adjusted stage-wise p-value (1)                    0.4296                                 
Adjusted stage-wise p-value (2)                    0.0424          0.0594                 
Adjusted stage-wise p-value (3)                    0.0125          0.0149                 
Overall adjusted test statistic (1, 2, 3)           1.779           2.591                 
Overall adjusted test statistic (1, 2)              1.374           2.074                 
Overall adjusted test statistic (1, 3)              1.959           2.922                 
Overall adjusted test statistic (2, 3)              1.959           2.718                 
Overall adjusted test statistic (1)                 0.177                                 
Overall adjusted test statistic (2)                 1.724           2.322                 
Overall adjusted test statistic (3)                 2.240           3.121                 
Test action: reject (1)                             FALSE           FALSE                 
Test action: reject (2)                             FALSE           FALSE                 
Test action: reject (3)                             FALSE            TRUE                 
Conditional rejection probability (1)              0.0101                                 
Conditional rejection probability (2)              0.0756          0.2954                 
Conditional rejection probability (3)              0.1317          0.5764                 
95% repeated confidence interval (1)       [-1.901; 2.081]                                
95% repeated confidence interval (2)       [-1.068; 2.768] [-0.227; 1.747]                
95% repeated confidence interval (3)       [-0.798; 2.998] [0.041 ; 2.051]                
Repeated p-value (1)                                 &gt;0.5                                 
Repeated p-value (2)                               0.2789          0.0518                 
Repeated p-value (3)                               0.1915          0.0189                 

Legend:
  (i): results of treatment arm i vs. control arm
  (i, j, ...): comparison of treatment arms 'i, j, ...' vs. control arm</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>stageResults <span class="ot">&lt;-</span> <span class="fu">getAnalysisResults</span>(<span class="at">design =</span> design,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dataInput =</span> dataExample, <span class="at">thetaH0 =</span> <span class="dv">0</span>, <span class="at">stage =</span> <span class="dv">2</span>,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">TRUE</span>, <span class="at">normalApproximation =</span> normalApproximation,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">intersectionTest =</span> <span class="st">"Simes"</span>, <span class="at">varianceOption =</span> varianceOption)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(stageResults)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Multi-arm analysis results for a continuous endpoint (3 active arms vs. control)

Sequential analysis with 3 looks (inverse normal combination test design).
The results were calculated using a multi-arm t-test (one-sided), 
Simes intersection test, overall pooled variances option.
H0: mu(i) - mu(control) = 0 against H1: mu(i) - mu(control) &gt; 0.

Stage                                                   1               2               3 
Fixed weight                                        0.577           0.577           0.577 
Efficacy boundary (z-value scale)                   3.471           2.454           2.004 
Cumulative alpha spent                             0.0003          0.0072          0.0250 
Stage level                                        0.0003          0.0071          0.0225 
Cumulative effect size (1)                          0.090                                 
Cumulative effect size (2)                          0.850           0.758                 
Cumulative effect size (3)                          1.100           1.052                 
Cumulative (pooled) standard deviation              1.597           1.468                 
Stage-wise test statistic (1)                       0.178                                 
Stage-wise test statistic (2)                       1.745           1.582                 
Stage-wise test statistic (3)                       2.283           2.226                 
Stage-wise p-value (1)                             0.4296                                 
Stage-wise p-value (2)                             0.0424          0.0594                 
Stage-wise p-value (3)                             0.0125          0.0149                 
Adjusted stage-wise p-value (1, 2, 3)              0.0376          0.0297                 
Adjusted stage-wise p-value (1, 2)                 0.0848          0.0594                 
Adjusted stage-wise p-value (1, 3)                 0.0251          0.0149                 
Adjusted stage-wise p-value (2, 3)                 0.0251          0.0297                 
Adjusted stage-wise p-value (1)                    0.4296                                 
Adjusted stage-wise p-value (2)                    0.0424          0.0594                 
Adjusted stage-wise p-value (3)                    0.0125          0.0149                 
Overall adjusted test statistic (1, 2, 3)           1.779           2.591                 
Overall adjusted test statistic (1, 2)              1.374           2.074                 
Overall adjusted test statistic (1, 3)              1.959           2.922                 
Overall adjusted test statistic (2, 3)              1.959           2.718                 
Overall adjusted test statistic (1)                 0.177                                 
Overall adjusted test statistic (2)                 1.724           2.322                 
Overall adjusted test statistic (3)                 2.240           3.121                 
Test action: reject (1)                             FALSE           FALSE                 
Test action: reject (2)                             FALSE           FALSE                 
Test action: reject (3)                             FALSE            TRUE                 
Conditional rejection probability (1)              0.0101                                 
Conditional rejection probability (2)              0.0756          0.2954                 
Conditional rejection probability (3)              0.1317          0.5764                 
95% repeated confidence interval (1)       [-1.901; 2.081]                                
95% repeated confidence interval (2)       [-1.068; 2.768] [-0.227; 1.747]                
95% repeated confidence interval (3)       [-0.798; 2.998] [0.041 ; 2.051]                
Repeated p-value (1)                                 &gt;0.5                                 
Repeated p-value (2)                               0.2789          0.0518                 
Repeated p-value (3)                               0.1915          0.0189                 

Legend:
  (i): results of treatment arm i vs. control arm
  (i, j, ...): comparison of treatment arms 'i, j, ...' vs. control arm</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="bonus-exercise-6-planning-of-survival-design" class="level1 unnumbered">
<h1 class="unnumbered">Bonus Exercise 6 (Planning of survival design)</h1>
<p>A survival trial is planned to be performed with one interim stage and using an O’Brien &amp; Fleming type <span class="math inline">\(\alpha\)</span>-spending approach at <span class="math inline">\(\alpha = 0.025\)</span>. The interim is planned to be performed after half of the necessary events were observed. It is assumed that the median survival time is 18 months in the treatment group, and 12 months in the control. Assume that the drop-out rate is 5% after 1 year and the drop-out time is exponentially distributed.</p>
<section id="exercise-6a-accrual-and-follow-up-time-given" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-6a-accrual-and-follow-up-time-given">Exercise 6a (accrual and follow-up time given)</h2>
<p>The patients should be recruited within 12 months assuming uniform accrual. Assume an additional follow-up time of 12 months, i.e., the study should be conducted within 2 years. Calculate the necessary number of events and patients (total and per month) in order to reach power 90% with the assumed median survival times if the survival time is exponentially distributed. Under the postulated assumption, estimate interim and final analysis time.</p>
<p><strong>Solution</strong></p>
<p>In this simplest example, accrual and follow-up time needs to be specified. The effect size is defined in terms of lambda1 and lambda2 (you can also specify lambda2 and hazardRatio).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>dGS <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>, <span class="at">beta =</span> <span class="fl">0.1</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">getLambdaByMedian</span>(<span class="dv">18</span>), <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="dv">12</span>, <span class="at">followUpTime =</span> <span class="dv">12</span>)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(x1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample size calculation for a survival endpoint

Sequential analysis with a maximum of 2 looks (group sequential design), overall 
significance level 2.5% (one-sided).
The sample size was calculated for a two-sample logrank test, 
H0: hazard ratio = 1, H1: treatment lambda(1) = 0.039, control lambda(2) = 0.058, 
accrual time = 12, accrual intensity = 38.9, dropout rate(1) = 0.05, 
dropout rate(2) = 0.05, dropout time = 12, power 90%.

Stage                                         1      2 
Information rate                            50%   100% 
Efficacy boundary (z-value scale)         2.963  1.969 
Overall power                            0.2525 0.9000 
Expected number of subjects               467.3 
Number of subjects                        467.3  467.3 
Cumulative number of events               128.3  256.5 
Analysis time                              13.1   24.0 
Expected study duration                    21.3 
Cumulative alpha spent                   0.0015 0.0250 
One-sided local significance level       0.0015 0.0245 
Efficacy boundary (t)                     0.593  0.782 
Exit probability for efficacy (under H0) 0.0015 
Exit probability for efficacy (under H1) 0.2525 

Legend:
  (t): treatment effect scale</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x1<span class="sc">$</span>maxNumberOfEvents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 257</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x1<span class="sc">$</span>maxNumberOfSubjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 468</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x1<span class="sc">$</span>maxNumberOfSubjects)<span class="sc">/</span><span class="dv">12</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>x1<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 13.14114
[2,] 24.00000</code></pre>
</div>
</div>
</section>
<section id="exercise-6b-follow-up-time-and-absolue-intensity-given" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-6b-follow-up-time-and-absolue-intensity-given">Exercise 6b (follow-up time and absolue intensity given)</h2>
<p>Assume that 25 patients can be recruited each month and that there is uniform accrual. Estimate the necessary accrual time if the planned follow-up time remains unchanged.</p>
<p><strong>Solution</strong></p>
<p>Here the end of accrual and the number of patients is calculated at given follow-up time and absolute accrual intensity:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(dGS, <span class="at">hazardRatio =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="dv">0</span>, <span class="at">accrualIntensity =</span> <span class="dv">25</span>, <span class="at">followUpTime =</span> <span class="dv">12</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x2<span class="sc">$</span>maxNumberOfSubjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 435</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>x2<span class="sc">$</span>accrualTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.38334</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>x2<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 16.79806
[2,] 29.38334</code></pre>
</div>
</div>
</section>
<section id="exercise-6c-accrual-time-and-max-number-of-patients-given" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-6c-accrual-time-and-max-number-of-patients-given">Exercise 6c (accrual time and max number of patients given)</h2>
<p>Assume that accrual stops after 16 months with 25 patients per month, i.e., after 400 patients were recruited. What is the estimated necessary follow-up time?</p>
<p><strong>Solution</strong></p>
<p>At given accrual time and number of patients, the follow-up time is calculated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>x3 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">16</span>), <span class="at">accrualIntensity =</span> <span class="dv">25</span>)</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x3<span class="sc">$</span>maxNumberOfSubjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 400</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>x3<span class="sc">$</span>followUpTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.96226</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>x3<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 16.82864
[2,] 31.96226</code></pre>
</div>
</div>
</section>
<section id="exercise-6d-staggered-patient-entry" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-6d-staggered-patient-entry">Exercise 6d (staggered patient entry)</h2>
<p>How do the results change if in the first 3 months 15 patients, in the second 3 months 20 patients, and after 6 months 25 patients per month can be accrued?</p>
<p><strong>Solution</strong></p>
<p>This is the result from b), where the end of accrual is calculated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>x4 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">6</span>), <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>), <span class="at">followUpTime =</span> <span class="dv">12</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x4<span class="sc">$</span>maxNumberOfSubjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 434</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>x4<span class="sc">$</span>accrualTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  3.00000  6.00000 19.14067</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>x4<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 18.48715
[2,] 31.14067</code></pre>
</div>
</div>
<p>This is the result from c), where the follow-up time is calculated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>x5 <span class="ot">&lt;-</span> <span class="fu">getSampleSizeSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">16</span>), <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>))</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ceiling</span>(x5<span class="sc">$</span>maxNumberOfSubjects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 355</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>x5<span class="sc">$</span>followUpTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.60973</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>x5<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 18.83368
[2,] 39.60973</code></pre>
</div>
</div>
<hr>
</section>
</section>
<section id="bonus-exercise-7-adaptive-survival-design" class="level1 unnumbered">
<h1 class="unnumbered">Bonus Exercise 7 (Adaptive survival design)</h1>
<section id="exercise-7a-verify-results-by-simulation" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-7a-verify-results-by-simulation">Exercise 7a (verify results by simulation)</h2>
<p>Assume that the study from Example 6 is planned with 257 events and 400 patients under the assumptions that accrual stops after 16 months with 25 patients per month. Verify by simulation the correctness of the results obtained by the analytical formulae.</p>
<p><strong>Solution</strong></p>
<p>We first calculate the analysis times by the analytical formulas and verify that the power is indeed exceeding 90%:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>y3 <span class="ot">&lt;-</span> <span class="fu">getPowerSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>,</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">16</span>), <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>),</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfEvents =</span> <span class="dv">257</span>, <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-6"><a href="#cb92-6" aria-hidden="true" tabindex="-1"></a>y3<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 18.85699
[2,] 39.74904</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>y3<span class="sc">$</span>overallReject  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9005251</code></pre>
</div>
</div>
<p>Practically the same result is obtained with the simulation tool:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>maxiter <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>z3 <span class="ot">&lt;-</span> <span class="fu">getSimulationSurvival</span>(dGS, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">dropoutRate1 =</span> <span class="fl">0.05</span>, <span class="at">dropoutRate2 =</span> <span class="fl">0.05</span>, <span class="at">dropoutTime =</span> <span class="dv">12</span>, <span class="at">maxNumberOfIterations =</span> maxiter,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">16</span>), <span class="at">accrualIntensity =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>),</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">plannedEvents =</span> <span class="fu">c</span>(<span class="dv">129</span>, <span class="dv">257</span>), <span class="at">directionUpper =</span> <span class="cn">FALSE</span>)</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>z3<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]
[1,] 18.91786
[2,] 39.58647</code></pre>
</div>
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>z3<span class="sc">$</span>overallReject  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.903</code></pre>
</div>
</div>
</section>
<section id="exercise-7b-assess-adaptive-survival-design" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exercise-7b-assess-adaptive-survival-design">Exercise 7b (assess adaptive survival design)</h2>
<p>Assume now that a sample size increase up to a ten-fold of the originally planned number of events is foreseen. Conditional power 90% <em>based on the observed hazard ratios</em> is used to increase the number of events. Assess by simulation the magnitude of power increase when using the appropriate method.</p>
<p>Simulate the Type I error rate when using</p>
<ul>
<li><p>the group sequential method</p></li>
<li><p>the inverse normal method</p></li>
</ul>
<p>Hint: Make sure that enough subjects are used in the simulation (set <code>maxNumberOfSubjects = 3000</code> and no drop-outs)</p>
<p><strong>Solution</strong></p>
<p>First define an inverse normal design with the same parameters as the original group sequential design:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>dIN <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>, <span class="at">beta =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>z4 <span class="ot">&lt;-</span> <span class="fu">getSimulationSurvival</span>(dIN, <span class="at">lambda1 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">18</span>, <span class="at">lambda2 =</span> <span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span><span class="dv">12</span>,</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfIterations =</span> maxiter,</span>
<span id="cb101-3"><a href="#cb101-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">16</span>), <span class="at">maxNumberOfSubjects =</span> <span class="dv">3000</span>, <span class="at">plannedEvents =</span> <span class="fu">c</span>(<span class="dv">129</span>, <span class="dv">257</span>), </span>
<span id="cb101-4"><a href="#cb101-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">FALSE</span>, <span class="at">conditionalPower =</span> <span class="fl">0.9</span>, </span>
<span id="cb101-5"><a href="#cb101-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">minNumberOfEventsPerStage =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>), <span class="at">maxNumberOfEventsPerStage =</span> <span class="dv">10</span><span class="sc">*</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>))</span>
<span id="cb101-6"><a href="#cb101-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb101-7"><a href="#cb101-7" aria-hidden="true" tabindex="-1"></a>z4<span class="sc">$</span>analysisTime</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]
[1,]  5.586818
[2,] 11.139290</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>z4<span class="sc">$</span>overallReject  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.982</code></pre>
</div>
</div>
<p>The following simulation compares the Type I error rate of the inverse normal method with the type I error rate of the (illegal) use of the group-sequential method:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>maxiter <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a>dGS <span class="ot">&lt;-</span> <span class="fu">getDesignGroupSequential</span>(<span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a>dIN <span class="ot">&lt;-</span> <span class="fu">getDesignInverseNormal</span>(<span class="at">kMax =</span> <span class="dv">2</span>, <span class="at">typeOfDesign =</span> <span class="st">"asOF"</span>)</span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-6"><a href="#cb105-6" aria-hidden="true" tabindex="-1"></a>IN <span class="ot">&lt;-</span> <span class="fu">getSimulationSurvival</span>(dIN, <span class="at">hazardRatio =</span> <span class="dv">1</span>,</span>
<span id="cb105-7"><a href="#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfIterations =</span> maxiter,</span>
<span id="cb105-8"><a href="#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">16</span>), <span class="at">maxNumberOfSubjects =</span> <span class="dv">3000</span>, <span class="at">plannedEvents =</span> <span class="fu">c</span>(<span class="dv">129</span>, <span class="dv">257</span>), </span>
<span id="cb105-9"><a href="#cb105-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">FALSE</span>, <span class="at">conditionalPower =</span> <span class="fl">0.9</span>, </span>
<span id="cb105-10"><a href="#cb105-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">minNumberOfEventsPerStage =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>), <span class="at">maxNumberOfEventsPerStage =</span> <span class="dv">10</span><span class="sc">*</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>))</span>
<span id="cb105-11"><a href="#cb105-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-12"><a href="#cb105-12" aria-hidden="true" tabindex="-1"></a>GS <span class="ot">&lt;-</span> <span class="fu">getSimulationSurvival</span>(dGS, <span class="at">hazardRatio =</span> <span class="dv">1</span>,</span>
<span id="cb105-13"><a href="#cb105-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfIterations =</span> maxiter,</span>
<span id="cb105-14"><a href="#cb105-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">accrualTime =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">16</span>), <span class="at">maxNumberOfSubjects =</span> <span class="dv">3000</span>, <span class="at">plannedEvents =</span> <span class="fu">c</span>(<span class="dv">129</span>, <span class="dv">257</span>), </span>
<span id="cb105-15"><a href="#cb105-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">directionUpper =</span> <span class="cn">FALSE</span>, <span class="at">conditionalPower =</span> <span class="fl">0.9</span>, <span class="at">minNumberOfEventsPerStage =</span> <span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>), </span>
<span id="cb105-16"><a href="#cb105-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxNumberOfEventsPerStage =</span> <span class="dv">10</span><span class="sc">*</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="dv">128</span>))</span>
<span id="cb105-17"><a href="#cb105-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb105-18"><a href="#cb105-18" aria-hidden="true" tabindex="-1"></a>IN<span class="sc">$</span>overallReject  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0274</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a>GS<span class="sc">$</span>overallReject  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0366</code></pre>
</div>
</div>
<hr>
<p>System: rpact 3.3.1, R version 4.2.2 (2022-10-31 ucrt), platform: x86_64-w64-mingw32</p>
<p>print(citation(“rpact”), bibtex = FALSE)</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>