---
title: "BBS seminar risk quantification: analysis of registrations"
author: "Kaspar Rufibach"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

path <- paste(getwd(), "/", sep = "")

source(paste("C:/rufibach/70_Service/BBS/webpage/home/tools/colFmt.r", sep = ""))

packs <- c("readxl", "dplyr", "rnaturalearth", "rnaturalearthdata", "ggplot2", "RColorBrewer", "filesstrings", "reporttools") 
for (i in 1:length(packs)){library(packs[i], character.only = TRUE)}

path <- "C:/rufibach/20_Research/25_sessions/20230412_BBS_Safety/registrations/"

path.data     <- paste(path, "data/", sep = "")
path.code     <- paste(path, "code/", sep = "")
path.depot    <- "C:/rufibach/05_Depot/"
path.map      <- paste(path.depot, "mapping/", sep = "")

source(paste(path.code, "prepTable.r", sep = ""), echo = FALSE)

## input and prepare registration data
source(paste(path.code, "input_prepare_data.r", sep = ""), echo = FALSE)
source(paste(path.code, "isValidEmail.r", sep = ""), echo = FALSE)

source(paste(path, "p0_initialize.r", sep = ""))
source(paste(path, "code/input_prepare_data.r", sep = ""), echo = FALSE)

# categories with frequencies below cut will be lumped together
cut <- 0

now <- as.POSIXlt(Sys.time())
now <- paste(substr(now, 1, 10), " at ", substr(now, 12, 19), sep = "")
```

# Data status

Data as of `r now`.

# Registrations by type of institution

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 10}
t2 <- with(reg2, table(type))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 2, mar = c(21, 4.5, 3, 1))
ylim <- c(0, 1.4 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste("Total number of registrations: ", dim(reg)[1], "\n type of institution", sep = ""), col = 2, ylim = ylim)
text(x = xx, y = t2, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, offset = 2, cex = 0.8, col = 1, srt = 90)
```

# Registrations by background

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 10}
t2 <- with(reg2, table(background))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 2, mar = c(21, 4.5, 3, 1))
ylim <- c(0, 1.4 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste("Total number of registrations: ", dim(reg)[1], "\n background", sep = ""), col = 2, ylim = ylim)
text(x = xx, y = t2, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, offset = 2, cex = 0.8, col = 1, srt = 90)
```

# Registrations by institution

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 10}
cut <- 2
t2 <- with(reg2, table(inst2))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 2, mar = c(21, 4.5, 3, 1))
ylim <- c(0, 1.4 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste("Total number of registrations: ", dim(reg2)[1], "\n institution", sep = ""), col = 4, ylim = ylim)
text(x = xx, y = t2, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, offset = 2, cex = 0.8, col = 1, srt = 90)
```
 
# Registrations of regulatory colleagues

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 10}
cut <- 0
t2 <- with(filter(reg2, type == "Regulator"), table(inst2))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 2, mar = c(21, 4.5, 3, 1))
ylim <- c(0, 1.4 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste("Total number of registrations: ", dim(reg2)[1], "\n regulatory colleagues", sep = ""), col = 4, ylim = ylim, yaxt = "n")
axis(2, at = 0:100, labels = 0:100)
text(x = xx, y = t2, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, offset = 1, cex = 0.8, col = 1)
```

# Registrations by countries

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 10}
t2 <- with(reg2, table(country2))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 2, mar = c(17, 4.5, 3, 1))
ylim <- c(0, 1.4 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste(dim(reg2)[1], " registrations from ", with(reg2, length(unique(country2))), " countries", sep = ""), col = 4, ylim = ylim)
#par(srt = 90)
text(x = xx + 0.2, y = t2 + 2.5, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, offset = 2, cex = 0.8, col = 1, srt = 90)
```

# Registrations by countries - map

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 15, fig.height = 10}
world <- ne_countries(scale = "medium", returnclass = "sf")

uc <- unique(reg2$country2)
uc <- uc[is.na(uc) == FALSE]
world$fill <- (world$sovereignt %in% uc) == FALSE

palette = colorRampPalette(brewer.pal(n=5, name='Oranges'))(5)
palette = c("white", palette)

worldpopmap <- ggplot() +
  geom_sf(data = world, aes(fill = fill)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.position = "none") +
  ggtitle("Broad representation") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(plot.title=element_text(size=30,face="bold"))

# display map
worldpopmap
```

# Registrations by mode of attendance

```{r, echo = FALSE, fig.cap = "", fig.align = "center", fig.width = 7, fig.height = 6}
t2 <- with(reg2, table(mode))
t2 <- prepTable(t2 = t2, cut = cut)

par(las = 1, mar = c(4.5, 4.5, 3, 1))
ylim <- c(0, 1.1 * max(t2))
xx <- barplot(t2, ylab = "number of registrations", main = paste("Total number of registrations: ", dim(reg)[1], "\n mode of attendance", sep = ""), col = 2, ylim = ylim)
text(x = xx, y = t2, label = paste(t2, " (", round(100 * t2 / sum(t2)), "%)", sep = ""), pos = 3, cex = 0.8, col = 1)
```










