```{r echo = FALSE}
# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434

i <- as.numeric('{{i}}')
tab <- filter(talks, date == dates[i])
meta <- tab[1, ]
```

# `r paste(as.character(meta$date), ": ", meta$seminar_title, sep = "")` {-}

[Program](`r paste("talks/", rdate[i], "/agenda.pdf", sep = "")`)

`r if (is.na(select(meta, recording)) == FALSE){paste("[Recording](", select(meta, recording)[, 1], ")", sep = "")} else {"No recording available"}`

`r if (is.na(select(meta, summary)) == FALSE){paste("[Summary of the event](talks/", rdate[i], "/summary.html)", sep = "")}`

```{r echo = FALSE}
links <- paste("[link](talks/", rdate[i], "/", select(tab, slides)[, 1], ")", sep = "")

# replace template links by external-pointing links, if available
ind <- (is.na(select(tab, link)) == FALSE)
links[ind] <- tab$link[ind]

tab2 <- data.frame(cbind(select(tab, speaker, company, title), links))
colnames(tab2) <- c("Speaker", "Institution", "Title", "Download slides")

# replace empty links
tab2[is.na(select(tab, slides)[, 1]), "Download slides"] <- "No presentation available"

# replace other empty entries
tab2[is.na(tab2)] <- ""

if (is.na(meta$speaker) == FALSE){kable(tab2)}
```
